### ISSUE TITLE
Changing Tree.Node interface

### ISSUE THREAD

**Issue by manu-m** [vavr-io/vavr#1023]
I really like javaslang's Tree implementation. It simplifies working with trees very much. Traversing, filtering etc. is much easier and more readable.

But I think the Tree/Tree.Node classes could be even more powerful if their methods don't work with the node's value but with the node itself. In some situations it is necessary to have a broader context. A simple example is to get all leafs of the tree. If the filter function expects a `Predicate<Tree.Node<T>>`, we could do something like:

``` java
tree.traverse().filter(Tree.Node::isLeaf)
```

respectivly

``` java
tree.filter(Tree.Node::isLeaf)
```

Really cool, I think ;-)

To make the context even broader it would be nice if a Tree.Node object references its parent node. I have had several situations where I wanted to know something about the node's parent or siblings while traversing and filtering. 

Following code snippet example shows that it is very easy to find the count of brothers and sisters of each member in a family tree, if the methods of Tree.Node (in this case toMap) expects a callback interface that excepts a Tree.Node that references its parent.

``` java
class Human
{
    private String name;
    private Gender gender;
}

Tree<Human> familyTree = /* initialization if family tree */;

membersBrothersAndSistersCount = 
  familyTree.toMap(humanNode -> {
      Tuple2<Seq<Gender>, Seq<Gender>> genders = humanNode.getParent().getChildren()
                  .map(Tree.Node::getValue)
                  .map(Human::getGender)
                  .partition(g -> g == Gender.MALE);

      Tuple2<Integer, Integer> brothersAndSistersCount = Tuple.of(
          genders._1().size(),  // brothers count
          genders._2().size()   // sisters count
      );

      return Tuple.of(humanNode.getValue().getName(), brothersAndSistersCount);
  })
```

What do you think about these ideas? I am very curious about your concerns ;-)

**Comment by danieldietrich** [comment]
I think you are right. This may come handy when processing syntax trees, the main reason I added a generic tree impl. Are you interested in doing these changes? I would greatly appreciate it!

**Comment by manu-m** [comment]
I will take a look on the sources within the next days. I hope I am able to implement these changes. At first let us define the requirements. A first draft:

**1) Changing Tree interface**
Tree interface should be changed from

```java
public interface Tree<T> extends Traversable<T>
```
to
```java
public interface Tree<T> extends Traversable<Node<T>>
```
*This change seems to be trivial in general but I suspect that it desires many changes in implementations of this interface and their tests. I'm not sure if I'm able to do this in a proper way because I'm not very deep into javaslang's implementation details. But let me see what I can do.*

**2) Parent reference in Tree/Tree.Node**
Tree/Tree.Node should reference it's parent. The parent of a node can be retrieved by calling:
```java
Option<Node<T>> getParent()
```
If returned Option object is empty, the node does not have a parent. 

Following questions have to be discussed in more detail for parent feature:

1. Should the getParent method be added to Tree or to Tree.Node? Tree seems to be the better place because tree already contains methods like isLeaf, isBranch etc.
2. How, when and by whom can the parent of a node assigned? Node objects are currently immutable and I think that's good. But how to respect this? I think being completely immutable will be hard because of the bidirectional parent-child relationship. My first idea is to set the parent of all children in the Node's constructor. This approach ensures at least that the parent cannot be modified from outside.

```java
private Node<T> parent;

public Node(T value, List<Node<T>> children) {
    //...
    this.children = children.peek(child -> child.setParent(this));
    //...
}

private void setParent(Node<T> parent)
{
    this.parent = parent;
}

@Override
public Option<Node<T>> getParent()
{
    return Option.of(parent);
}

**Comment by ruslansennov** [comment]
What about something like this?
```java
private final Node<T> parent;

public Node(T value, List<Node<T>> children, Node<T> parent) {
    //...
    this.children = children.peek(child -> child.setParent(this));
    this.parent = parent;
    //...
}

public Node<T> setParent(Node<T> parent) {
    return new Node<>(this.value, this.children, parent);
}
```

**Comment by danieldietrich** [comment]
@manu-m @ruslansennov I had once an immutable Tree impl. But the update operations were non-trivial. Here is the old version: https://github.com/javaslang/javaslang/blob/parser/src/main/java/javaslang/collection/Tree.java

That version has no Leaf/Node interfaces. Because of the immutability, operations on tree nodes take O(n). A copy of the whole tree is needed on each operation - in both directions: up to the root, down to the children - and the tricky part: from the parent down to the children other than the current node. And for these the same procedure. This logic is abstracted in TreeTransformer (see link above).

I have to sleep one night over this topic to get a clear picture if it really makes sense to add parent nodes and how this could be achieved. For example we could maintain an immutable tree without parent nodes and decorate it with a lazy view on that tree, which is constructed while traversed, adding the parent information only if needed. This would reduce the complexity of operations.

**Example:**

Here I will use `<T>` because it is simpler for me.

We already have this (without parents):

```java
Tree.of(t1, Tree.of(t2), Tree.of(t3))
```

results in

```
     Node(t1)
    /       \
Node(t2)  Node(t2)
```

We could now return a TreeView on a Tree which adds parents:

```java
Tree<T> tree = Tree.of(t1, Tree.of(t2), Tree.of(t3));

// internally calls new TreeView(Option.none(), tree);
TreeView<T> withParents = tree.withParents();
```

with this implementation:

```java
interface TreeView<T> extends Tree<T>, HasParent<T> {

    List<NodeView<T>> getChildren();
}

final class NodeView<T> implements TreeView<T>, Serializable {

    final Option<NodeView<T>> parent;
    final Node<T> node;
    final Lazy<List<NodeView<T>>> children;

    NodeView(Option<NodeView<T>> parent, Node<T> node) {
        this.parent = parent;
        this.node = node;
        this.children = Lazy.of(() -> node.getChildren().map(child -> new NodeView<>(this, child)));
    }
}

interface HasParent<T> {
	boolean isRoot;
	Option<TreeView<T>> getParent();
}
```

Currently the use of Tree, Node, Empty is messed up a little bit. The empty() and of() methods should return Tree instead of Node and Empty. To check if the main idea of using views works we need a proof of concept.

**Comment by danieldietrich** [comment]
@manu-m I think we should do the changes step by step, as you suggested. First we change the interface to `public interface Tree<T> extends Traversable<Node<T>>`. That will be a good 'warmup'. After that we add the parents. It is good to separate these two things.

**Comment by danieldietrich** [comment]
This needs to be done before 2.0.0 because it changes the interface. I will do that along with root references with views as I suggested.

**Comment by danieldietrich** [comment]
We can't make `Tree<T>` extends `Traversable<Node<T>>` instead of `Traversable<T>` because overloaded can't return `Tree<Node<T>>`. The compiler wants a `Traversable<Node<T>>`. There is nothing we can do about that.

My suggested solution: Our `Tree.traverse()` method will return `Seq<Node<T>>` instead of `Seq<T>`. Then we have all possibilities.

**Comment by danieldietrich** [comment]
I think with the last additions we are safe to make 2.0.0 final. The existing interface methods need not to be modified in order to add the root reference later.

**Comment by danieldietrich** [comment]
Parent references will be added next release.

**Comment by danieldietrich** [comment]
Tree is dropped in Vavr 1.0

**Comment by romildo** [comment]
>Tree is dropped in Vavr 1.0

There will be a replacement for it?

I am using Vavr on my compiler classes because of Tree.

**Comment by danieldietrich** [comment]
It will be added to Vavr 1.1 as part of the vavr-collectionx module, along with BitSet, PriorityQueue, MultiMap and MultiSet.

I suggest to you to wait for 1.1 then.
