### ISSUE TITLE
[type hierarchy] Change Iterator not to inherit from Iterable

### ISSUE THREAD

**Issue by mvh77** [vavr-io/vavr#1295]
As  javaslang Iterator is iterable, it has an iterator() method, but currently it returns this, which breaks the contract of Iterable. It should always return a new iterator that can be traversed. This prints both foo and bar twice in scala but not with javaslang:

``` scala
def printTwice[T](it: Iterable[T]) = {
  it.iterator.foreach(println)
  it.iterator.foreach(println)
}

printTwice(Vector("foo"))
printTwice(Iterable("bar"))
```

This works differently with and without the call to .iterator() which IMO is not ok:

``` java
List<Integer> transform = List.of(1, 2, 3)
  .iterator()
  .transform(i -> List.ofAll(i).appendAll(i));
System.out.println(transform);
```

**Comment by ruslansennov** [comment]
Your javaslang code not consistent with your Scala code.
It should be something like this:

```java
public class It {

    private static <T> void printTwice(Iterable<T> it) {
        it.iterator().forEachRemaining(System.out::println);
        it.iterator().forEachRemaining(System.out::println);
    }

    public static void main(String[] args) {
        printTwice(Vector.of("foo"));   // print twice, ok
        printTwice(Iterator.of("bar")); // print once, ok
    }
}
```
I believe it is impossible to return a new iterator in <code>Iterator#iterator()</code> method because Iterator is mutable object.

**Comment by mvh77** [comment]
It's not the same code, but that's not the point. The point is that since Iterator is an Iterable, you can pass it to any method that expects an Iterable, and an Iterable is supposed to give you iterators that you can traverse the collection with. An Iterator can be iterated once, but an Iterable must provide new Iterators on all calls to iterator(). The method receiving the Iterable has no way to know that the Iterable provides the same Iterator every time.

Iterator needs to keep a reference to the sequence it was created with, that's how it can create new iterators on every call.

**Comment by danieldietrich** [comment]
Yep, I think Ruslan is right, we need to live with that caveat. There is a reason for that:

Scala's type hierarchy is different, `Iterable` extends `Traversable` and `Iterator` extends `Traversable`. Especially `Iterator` is not an `Interable`.

In Javaslang `Traversable` extends `Iterable` and `Iterator` extends `Traversable`. Especially `Iterator` is an `Iterable`.

Because of this difference and the fact that Iterator is stateful, we cannot create a new Iterator based on an Iterator.

**Comment by danieldietrich** [comment]
> Iterator needs to keep a reference to the sequence it was created with, that's how it can create new iterators on every call.

I'm not sure if this is possible. Trying to find a counter-example now...

**Comment by danieldietrich** [comment]
Example:

```java
final int[] i = { 0 };

Iterator<Integer> iter = new Iterator<Integer>() {

    @Override
    public boolean hasNext() {
        return true;
    }

    @Override
    public Integer next() {
        return i[0]++;
    }
};
```

**Comment by mvh77** [comment]
That's not a caveat that can be lived with. Iterator cannot extend Iterable if changing that is impossible...but I'm not convinced that it is.

I don't understand what your example shows. :smile:

**Comment by mvh77** [comment]
Ahh f*#$ this is a nightmare, anything that takes an Iterable can break if given a javaslang Iterator... Iterator#iterator() should at least throw an UnsupportedOperationException or something.

**Comment by danieldietrich** [comment]
We needed `Iterator` to create Set and Map impls in an efficient/concise way. Basically you are right. But if we forget what we know from Scala, the [java.util.Iterator API](https://docs.oracle.com/javase/8/docs/api/java/lang/Iterable.html#iterator--) does not say that subsequent calls of `iterator()` have to iterate the same elements. Actually the javadoc days:

```
Returns an iterator over elements of type T.
```

The focus is on

```
... over elements ...
```

In our case the elements are 'eaten'. A second `iterator()` will not have any elements. But is this really a problem? Or is it a problem that we expect to work differently because of Scala? Maybe it is sufficient to clarify the behavior.

I think Scala has a similar problem because List and Iterator are both TraversableOnce. But Iterator has the following limitation (from the Scala docs):

```
It is of particular importance to note that, unless stated otherwise, ''one should never
use an iterator after calling a method on it''. The two most important exceptions
are also the sole abstract methods: `next` and `hasNext`.
```

If we assign an Iterator to a val of type TraversableOnce, we can't know if we are allowed to make subsequent methods calls which lead to a defined behavior...

**Comment by mvh77** [comment]
I think it is a major problem, and not because of Scala, I think that is secondary. An IteraBLE is something you can iterate over, like a collection/stream. An IteraTOR is not something you can iterate over, it's the thing you iterate with.

In scala if you map over a list you immediately get a new list, so if you want to chain functionality in an efficient way without generating a new list every time, you transform it into an iterator first. Basically the same as a java stream, right? Just a wrapper for transformation functionality. I think that's what we should aim for as well. I don't see what benefits we get from having Iterator extend Traversable.

I guess this cannot be changed in 2.x.x, but what if in 3.0 Iterator only extends java.util.Iterator, and not Traversable and Value? Would that be a major problem?

**Comment by danieldietrich** [comment]
That should be no problem.

In order to reduce code duplication we could introduce the interface `TraversableOnce` like so:

```
Iterable
   ^
   |
 Value TraversableOnce
   ^   ^             ^
    \ /              |
Traversable      Interator
     ^ 
    /|\
Seq Set Map ...
```

**Comment by mvh77** [comment]
Looks good to me! :+1:

**Comment by danieldietrich** [comment]
## Notes

With #1810 we need to adjust which classes of the Traversable type hierarchy explicitly extend Serializable:

* Traversable will extend Serializable
* All other collection interfaces and classes will not (explicitly)

The calls `ofAll(iterator)` will be replaced by `ofAll(() -> iterator)`

**Comment by danieldietrich** [comment]
Done on the v1.0.0 branch. See also the blog post ["Purifying the API Surface Area"](http://blog.vavr.io/purifying-the-api-surface-area/).
