### ISSUE TITLE
Add more syntactic sugar to Validation

### ISSUE THREAD

**Issue by danieldietrich** [vavr-io/vavr#1565]
**Update: Follow #2073** and take this comment into account:

> widen Validation's List&lt;E> to List&lt;? extends E> in many cases.

---

Currently we have:

``` java
Validation<E, T1> v1 = ...
Validation<List<E>, T2> v2 = ...
Validation<List<E>, U> result = v1.ap(v2.map(t2 -> t1 -> f(t1, t2)));
```

We additionally need:
- `<T2, U> Validation<List<E>, U> append(Validation<List<E>, T2>, Function<? super T1, ? super T2, ? extends U>)` that _appends_ an error to an error list
- `<T2, U> Validation<List<E>, U> prepend(Validation<List<E>, T2>, Function<? super T1, ? super T2, ? extends U>)` that _prepends_ an error to an error list
- `static <E, T1, T2> Validation<List<E>, Tuple2<T1, T2>> combine(Validation<List<? extends E>, T1>, Validation<List<? extends E>, T2>)`
- ...
- `static <E, T1, T2, ..., T8> Validation<List<E>, Tuple8<T1, T2, ..., T8>> combine(Validation<List<? extends E>, T1>, Validation<List<? extends E>, T2>, ..., Validation<List<? extends E>, T8)`

**Note:** For release 3.0.0 we should widen `List<E>` to `List<? extends E>` in many cases. Also we should consider to change `Validation<List<E>, T>` to `Validation<Seq<E>, T>` and use `Vector` instead of `List`.

**Comment by io7m** [comment]
For the record, I tend to rewrite `flatten :: Validation<List<List<E>>, T> -> Validation<List<E>, T>` every time I use Validation, so perhaps something more generally typed than that would be useful.

**Comment by danieldietrich** [comment]
Java's type system does not allow us such a flatten method to be defined as instance method - it had to be a static method. However, it is uncommon to flatten the 'negative' (error) case. For example `Either.map()` and `Either.flatMap()` operate on the right value.

I think we need to prevent that `Validation<List<E>, Tn>` are combined to a `Validation<List<List<E>>, Tn>`. This could be accomplished by changing `Validation<E, T>` in the way that it implicitly has a list of errors instead of an error. I.e. `Invalid<E, T>.getError()` returns a `List<E>` instead of an `E`. Then we do not need to care about flattening any more at all. It is automatically done on each operation.

@io7m could you provide a complete (simple) example where it is necessary to flatten? Maybe the same could accomplished without flattening. I will take a look. Thank you!

**Comment by io7m** [comment]
Ok, so here's the intuitive example of using `Validation` to validate a trivial configuration format loaded from Java `Properties`. You have a mix of keys that can have integer values, string values, list-of-integer values, and list-of-string values. It makes sense for the scalar-valued keys to return a `Validation` that has a single error value, because there's really only one thing that can fail in each case. It makes sense for the list-valued keys to return a `Validation` that has a list of error values because there can be multiple errors present when parsing a list:

https://gist.github.com/io7m/8b8bf4c208e9a067a87786e8d8499097

Unfortunately, it appears that doing this requires some gymnastics to repeatedly either _flatten_ or _unflatten_ the errors to get the right type for the monadic bind, or for combining the validation values. It's also necessary to flatten the result of the `ap` call, because noone wants to be dealing with a list of a list of errors!

It might seem slightly better to instead just use a list of errors everywhere, and arguably it is slightly better:

https://gist.github.com/io7m/fd64fe18f9a94e83c1b64101e122aa1d

There's less in the way of flattening and unflattening lists of errors, but the manipulation that _is_ there seems slightly more painful. The final call to `ap` still needs to be flattened.

Note that I've not even run this code. It type checked so I assume that it's correct! :smile:

**Comment by danieldietrich** [comment]
Great many thanks - I will get my hands on it...

**Comment by io7m** [comment]
Here's a small one:

```
  public static Validation<List<RouteError>, List<RouteDirection>> parse(
    final String text)
  {
    return Validation.sequence(List.of(text.split(";")).map(name -> {
      try {
        return Validation.valid(RouteDirection.of(name));
      } catch (final IllegalArgumentException e) {
        return Validation.invalid(
          List.of(RouteError.of(e.getMessage(), Optional.of(e))));
      }
    })).map(List::ofAll);
  }
```

With the `Seq` change, that could become:

```
  public static Validation<Seq<RouteError>, List<RouteDirection>> parse(
    final String text)
  {
    return Validation.sequence(List.of(text.split(";")).map(name -> {
      try {
        return Validation.valid(RouteDirection.of(name));
      } catch (final IllegalArgumentException e) {
        return Validation.invalid(
          Vector.of(RouteError.of(e.getMessage(), Optional.of(e))));
      }
    }));
  }
```

... and with the addition of an `invalid` static method (probably with a different name to please the type checker) that wraps the given single value in a sequence, it could become:

```
  public static Validation<Seq<RouteError>, List<RouteDirection>> parse(
    final String text)
  {
    return Validation.sequence(List.of(text.split(";")).map(name -> {
      try {
        return Validation.valid(RouteDirection.of(name));
      } catch (final IllegalArgumentException e) {
        return Validation.invalid(RouteError.of(e.getMessage(), Optional.of(e));
      }
    }));
  }
```

I find myself writing that last one pretty frequently as I'm almost never returning a `Validation` with an error type that isn't a sequence of some sort.

**Comment by danieldietrich** [comment]
@io7m thank you for the example, it is good to see a use-case in practice.

> I'm almost never returning a Validation with an error type that isn't a sequence of some sort

I have to think about that. The most annoying thing currently is to deal with single invalid values and the step to sequences of invalid values on the type system. Especially when combining Validation instances.

**Comment by grzesiek-galezowski** [comment]
Hi, just wanted to ask, are you planning to give some more options to convert `Try` to `Validation`? For example, there is `Validation.fromEither`, but not something like `Validation.fromTry`.

**Comment by danieldietrich** [comment]
@grzesiek-galezowski we could do that! PR’s welcome ;)

**Comment by grzesiek-galezowski** [comment]
Thanks, I'll try to prepare something!

**Comment by danieldietrich** [comment]
Awesome!

**Comment by danieldietrich** [comment]
Validation in this form will probably not part of Vavr 1.0 - it does not scale well because of the restriction to Function8.
Instead we should think about a redesign from scratch or leave it away and stick to alternatives like Either.sequence...
