### ISSUE TITLE
Remove unnecessary casts by adding type hints

### ISSUE THREAD

**Issue by danieldietrich** [vavr-io/vavr#1935]
**Before**

```java
@SuppressWarnings("unchecked")
@Override
default <U> Seq<U> map(Function<? super Tuple2<K, V>, ? extends U> mapper) {
    Objects.requireNonNull(mapper, "mapper is null");
    // don't remove cast, doesn't compile in Eclipse without it
    return (Seq<U>) iterator().<U> map(mapper).toStream();
}
```

**After**

```java
@Override
default <U> Seq<U> map(Function<? super Tuple2<K, V>, ? extends U> mapper) {
    Objects.requireNonNull(mapper, "mapper is null");
    return iterator().<U> map(mapper).toStream();
}
```

**Comment by danieldietrich** [comment]
Casts come nearly with no costs. It is unrealistic that we are able not to use casts or check that casts aren't used in PRs.

**Comment by nfekete** [comment]
Cast would be problematic because it could make the code fail at runtime. The Eclipse compiler doesn't need those kind of casts most of the time (I can't recall a case where it needs them on otherwise valid code that works without casts in javac). Those Eclipse compiler vs javac compiler differences can be solved most of the time with type hints, which are things that help the inference engine but they are not casts. I think it's a good thing to aim for the whole code-base to be cast free, and limit casts to cases where it's both absolutely necessary and safe at the same time.

**Comment by danieldietrich** [comment]
> 

I think cast are widely used in practice. Example (Vavr 1.0 code-base):

```java
    @SuppressWarnings("unchecked")
    public <U> Try<U> flatMap(CheckedFunction<? super T, ? extends Try<? extends U>> mapper) {
        Objects.requireNonNull(mapper, "mapper is null");
        if (isSuccess()) {
            try {
                return (Try<U>) mapper.apply(get());
            } catch (Throwable t) {
                return failure(t);
            }
        } else {
            return (Try<U>) this;
        }
    }
```

I wouldn't say it is unsafe. A better wording would be that it is error-prone.

If we do it wrong, we need a bug fix. After that, it will work as expected.
