### ISSUE TITLE
NotImplementedError should be NotImplementedException

### ISSUE THREAD

**Issue by nfekete** [vavr-io/vavr#1961]
The javadoc of [`java.lang.Error`](https://docs.oracle.com/javase/8/docs/api/java/lang/Error.html) states that 
> An Error is a subclass of Throwable that indicates serious problems that a reasonable application should not try to catch. Most such errors are abnormal conditions.

I believe `NotImplementedError` should extend `RuntimeException` and should be called `NotImplementedException` instead, because something not being implemented can still be a recoverable error an application could, and probably should try to catch.

It mostly matters in generic error handling code that decides what to do based on exception classes: 

 * `RuntimeException` -> recover from it
 * `Error` -> try to log it and let the app die

**Comment by danieldietrich** [comment]
A `NotImplementedError` is _defined_ to be non-recoverable, like [Scala's NotImplementedError](http://www.scala-lang.org/api/current/scala/NotImplementedError.html).

From the Scala Docs:

> Throwing this exception can be a temporary replacement for a method body that remains to be implemented.

There is no room for interpretation.

We should close this ticket.

**Comment by nfekete** [comment]
This can be worked around quite easily even if it stays like it is now, but I think interpreting it as a recoverable error rather than non-recoverable makes more sense. Maybe the Scala people got it wrong in the first place?
This changeset is suggesting this might actually be the case:
https://github.com/scala/scala/commit/68f62d7e9c200034bd42ffaf795b57fb379d9d38
Also, this bug: https://issues.scala-lang.org/browse/SI-7164

I'm not familiar with Scala but it seems they have a separate mechanism to distinguish between fatal and non-fatal exceptions while Java, and more precisely, generic error handling code in Java uses the base Java exception categories: `Exception`, `RuntimeException`, `Error`.

I think the mistake was that they thought at first that it's similar to Java's `LinkageError` while in reality it's not, because `LinkageError` is thrown in an unexpected/invalid state where some binary incompatibility arose, while the `NotImplementedError` is pretty much intentional.

The question is whether we want to blindly copy Scala behavior even if it seems wrong or walk our own walk where appropriate?

**Comment by nfekete** [comment]
What if we would only change the superclass, but not the name? We could keep binary compatibility while subtly changing semantics towards the right way.

**Comment by danieldietrich** [comment]
Both `Error` and `RuntimeException` are unchecked exceptions, so _technically_ there is no difference.

`UnsupportedOperationException` is a good example for a _semantically_ missing implementation. It extends `RuntimeException` and has the (original) meaning that it is _intended_ that no implementation exists. It was necessary for Java to introduce it because of the Java Collection Framework's immutable classes.

Our `NotImplementedError` is another cup of tea. It can be thrown by using the `TODO()` method of API (similar to Scala's Predef`s `???`). The main use is in the field of rapid prototyping. We want rapidly get our code statically compile in order not to cope with the bloody details (for now):

```java
R compute(A a) {
    return TODO(/* Will do that later... */);
}

void run() {
    compute(TODO(/*call service1 to get an A*/)).doSomethingMeaningful();
}
```

A Program that contains `TODO()`s is wrong and should **not** go to production! The user should not try to handle `NotImplementedErrors`. These are more sort of **development-time errors** than runtime errors.

---

The Fatal / NonFatal discussion is a different story. It has only to do with the internal implementation of `Try` (in Scala and in ~~Javaslang~~ Vavr).

More specifically

```java
Try(() -> { throw new Err(); });
```

Will result in a `Failure` if Err is considered to be `NonFatal`. If it is considered to be `Fatal`, the application will re-throw the cause instead of creating a `Try` instance. That is all.

For example a `StackOverflowError` extends `VirtualMachineError` but is considered to be `NonFatal` because a flooded Stack is cleaned up by the JVM when the method body exists. But an `OutOfMemoryError` may mix up the program semantics. The program execution is non-deterministic in such a case.

Please see also Vavr's [Try.NonFatal](https://github.com/vavr-io/vavr/blob/5e9beadcd056b1d6e4d9b1bc046d1759deda1c69/vavr/src/main/java/io/vavr/control/Try.java#L1609-L1638).

Please note that this is subject to change. See #1382 and #1722. However, fatal exception will still be re-thrown in Vavr but exceptions need not to be wrapped anymore in NonFatal and Fatal :)

---

Trust me, extending `Error` is correct.

**Comment by danieldietrich** [comment]
I've recognized that we should re-introduce `StackOverflowError` as non-fatal exception. I will create an issue.

**Comment by nfekete** [comment]
`NotImplementedError` extending `Error` instead of `RuntimeException` doesn't prevent it from ending up in production. It depends on whether though pre-production testing of the app actually touches that code path or not. The only difference I see is how the application reacts to such an event.

Let's suppose there's an app shell providing the skeleton for the app (could be a container or some custom app skeleton). The skeleton/container is responsible for centralized error handling. The app skeleton/container contains a number of modules, and it's not even aware that one of the module uses vavr. The error handling code is some top level code that contains an exception handler that handles `Exception` subclasses to log them and to present the user with some meaningful error message ("This function is not implemented yet" is a meaningful user error message). The generic error handler also catches subclasses of `Error`, but only to log them, rethrowing afterwards, letting the app die, as there's no expected way to recover from such an error. This kind of generic error handling code is pretty common, I suppose a lot of frameworks/containers contain such error handling code.

In the end, we didn't necessarily prevent the app going into production (that's more a matter of proper testing), but made matters worse by letting our app die while we could just as easily recover from the exception.

I strongly believe `TODO` is a recoverable exception and we should treat is as such.

Also note that `Try.of(API::TODO)` returns a `Failure(javaslang.NotImplementedError: An implementation is missing.)`, while 
```java
Try.of(() -> {
    throw new LinkageError();
});
````
throws `Try.FatalException`, a subclass of `RuntimeException` which is pretty wrong, it converts a non-recoverable exception into a recoverable one. My point is that vavr already treats `NotImplementedError` as a recoverable exception, it just doesn't communicate it as such to the outside world (being a subclass of the non-recoverable `Error`).

This seems to be a useful discussion as it uncovered another possible issue, that of `FatalException` being a subclass of `RuntimeException`.

**Comment by danieldietrich** [comment]
I currently see no problem that arises. If in doubt, we always align to Scala.

We want to signal that it is semantically an `Error` if the underlying program runs into a `NotImplementedError`, regardless if it is recoverable or not.

**This is by definition.** It is part of our suggested programming model and part of the contract of the `TODO()` method.

Before having `TODO()`, the only possibility was to assign `null` to such code-parts. This could leak undefined behaviour into the code base. The job of `TODO()` resp. `NotImplementedError` is to put this right.

When we start to treat `NotImplementedError` as recoverable exception, the original idea of replacing `null` is broken again. It will lead to a JavaScript-like `undefined` state. We have to make clear that a `TODO()` is an error that has to be fixed by the developer.

---

`Try.Fatal` can be understood as

> Computer, stop now. Immediately.
> It makes no sense to do anything else than shutting down.
> Even writing something to the logs makes no sense anymore. It might end up in chaos.

But you are right, `Try` may leak a `NotImplementedError` into production, in every scenario we discussed so far.

However, I would leave it this way. Fatal exceptions are very rare. It means "shut down, now". It is more something 'physically broken'  than 'logically broken'. I would align to Scala here.

---

It was interesting to discuss about it because even something simple as an Exception may span a whole universe of aspects. For example I did not think about the dependency to Try.Fatal, yet.

However, sprinkling dependencies to something simple like `NotImplementedException` across the code-base is evil on its own. Before doing this I would consider to remove `TODO()` and `NotImplementedError` instead. Simplicity is the most important goal.

Let's close this ticket.

**Comment by nfekete** [comment]
> Before having TODO(), the only possibility was to assign null to such code-parts. This could leak undefined behaviour into the code base. The job of TODO() resp. NotImplementedError is to put this right.
>
>When we start to treat NotImplementedError as recoverable exception, the original idea of replacing null is broken again. It will lead to a JavaScript-like undefined state. We have to make clear that a TODO() is an error that has to be fixed by the developer.

I wasn't saying `TODO()` is a bad idea and we should use `return null;` instead, on the contrary, I think it's good practice, I just said that extending `RuntimeException` would be better than extending `Error`, because of semantics defined in the [`java.lang.Error`](https://docs.oracle.com/javase/8/docs/api/java/lang/Error.html) class javadoc. I see this as a very similar exception to [`UnsupportedOperationException`](https://docs.oracle.com/javase/8/docs/api/java/lang/UnsupportedOperationException.html), the only difference being the latter is not necessarily planned to be implemented later.

**Comment by danieldietrich** [comment]
Thanks. This issue is a good reference, I will take parts for the documentation.

**Comment by danieldietrich** [comment]
@nfekete (related)

I think the other way makes sense: making `NotImplementedError` fatal. We then ensure that it does not leak into a `Failure`.
