### ISSUE TITLE
Why vavr collections accept null?

### ISSUE THREAD

**Issue by m-titov** [vavr-io/vavr#2052]

**Comment by chb0github** [comment]
What do you mean? Like: `List.of(null)` ? Why not?

**Comment by m-titov** [comment]
Yes. Like that. Because why do we need it? It would be more useful to have garanted not null elements collection.

**Comment by chb0github** [comment]
Null is an entire legitimate value for a collection - consider a JSON array:

`[1,2,null,4,5]` -> If I couldn't Load this into a list as `List.of(1,2,null,4,5)` Then how could I ever use a collection type for serializing/deserializing?

As for collections that use the values added for identity purposes (`HashSet`,`TreeSet`, etc), that's why you can give it a comparator (in the case of tree-set) of `TreeSet.of(Comparator.nullsFirst(Comparator.comparing(MyObject::getProperty))`

I have made a case for Something similar with `HashSet.identifiedBy(MyObject::getProperty)` or something similar.

Regardless: `null` is a totally legitimate value. If you're expecting an exception to be thrown then you're looking at the wrong libraries - Exceptions are an anathema to functional programming as they are side-effects _by design_

For that, you could look at the apache collections and `PredicatedList`.

**Comment by m-titov** [comment]
https://github.com/google/guava/wiki/UsingAndAvoidingNullExplained

**Comment by m-titov** [comment]
` Exceptions are an anathema to functional programming as they are side-effects by design

Ok. Thanks

**Comment by chb0github** [comment]
Nulls are 'bad' as in they can lead to abnormal machine state and require a lot of code to handle them. But 'null' is a totally valid state. I see no reason vavr (as a library) should treat them special. 

You as the user can and should handle them as handling null is _NOT_ a cross cutting concern. Burying any logic low-down in a library is ill advised. 

Can we close the ticket?

**Comment by m-titov** [comment]
You probably right. Maybe exceptions are an anathema to functional programming. But I have never faced with null values in collections during long time. I think using null in collections is bad design of application. That's why currently I prefer guava to vavr.

> Can we close the ticket?
Yes. Thank you for your answer.

**Comment by nfekete** [comment]
@m-titov you might want to subscribe to issue https://github.com/vavr-io/vavr/issues/1919. It might be extended with information of your interest.
