### ISSUE TITLE
Create Try<Optional> utilities

### ISSUE THREAD

**Issue by skestle** [vavr-io/vavr#2099]
Given a method `Optional<T> retrieve(Id) throws Exception` and `R process(T) throws Exception`

I'd like to be able to get something close to
```
Try<Option<R>> result = Try.of(() -> Option.ofOptional(retrieve(id)))
    .andThenTry(Processor::process);
```

What I currently have to do is 
```
Try<Option<R> result = Try.of(() -> Option.ofOptional(retrieve(id)))
    .map(retrieved -> retrieved.map(t -> Try.of(() -> Processor.process(t))))
    .flatMap(processed -> Try.of(processed.map(Try::get))); // Try<Option<Try<R>>> -> Try<Option<R>>
```

That flatMap just does my head in (and possibly isn't the best for speed either)

The desired API is possible if we overload `TryOption<T> = Try.of(CheckedOptionFunction<T>)` where `interface CheckedOptionFunction<T> extends CheckedFunction0<Option<T>>`

but even some static utility would be awesome. (I think it could be common enough to be an awesome addition)

**Comment by danieldietrich** [comment]
Thanks!

I don't think we need a special construct. It is already all there.
Why not just use the following?

`Try.of(() -> Option.ofOptional(retrieve(id).map(Processor::process)))`

**Comment by nhinds** [comment]
If `Processor.process` throws an exception, I don't think it can be passed to `Optional.map` because [`Optional.map` takes a `java.util.Function`](https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html#map-java.util.function.Function-), and a `java.util.Function` isn't allowed to throw checked exceptions.

**Comment by danieldietrich** [comment]
Yes, you are right, I've overseen that.

What we need is `Option.mapTry` (and `Option.flatMapTry`):

```java
Try.of(() -> retrieve(id)).map(o -> Option.ofOptional(o).mapTry(this::process));
```

with

```java
interface Option<T> {
    default <U> Option<U> mapTry(CheckedFunction1<? super T, ? extends U> mapper) {
        if (isEmpty()) {
            return Option.none();
        } else {
            try {
                return Option.of(mapper.apply(get()));
            } catch(Throwable x) {
                return Option.none();
            }
        }
    }
}
```

**Comment by skestle** [comment]
I think that's why I'd like a construct - so it's not constrained by compatibility with `Option` or `Try`.

I don't want my `Success<Some<T>>` to become a <Success<None>>`. I need to know that the conversion from T to U is a `Failure`.

`Success<None>` of `U` implies that `T` was `None` as well.

So I want `TryOptional.map(T -> U)` that (semantically):
* `Success<Some<T>> -> Success<Some<U>>` - executed
* `Success<None> -> Success<None>`
* `Failure<T> - > Failure<U>`

I don't know about `TryOptional.flatMap`, but as a specialised type, I don't expect it needs to be fully defined monadically. I'd expect
* `Try<U> flatMap(T -> Try<U>)`
* `TryOptional<U> flatMap(T -> TryOptional<U>)`
Perhaps only the second is valid since this construct would be able to be deconstructed via `toOption` and `Try<Option<T>> to/asTry` - perhaps `toTry().flatMap(Value::toTry)` would be the basic form...

**Comment by danieldietrich** [comment]
@skestle I always think about how I can reduce Vavr, not how I can add more. I do not want to add new types for every new use-case. The existing abstractions should be powerful enough to achieve the desired by composition.

What's wrong with

```java
Try.of(() -> retrieve(id)).map(o -> Option.ofOptional(o).mapTry(Processor::process)
);
```

I think it fits your use-case. Especially no Success&lt;Some&lt;T>> is mapped to Success&lt;None&lt;U>>.

**Comment by skestle** [comment]
Yes that looks good. I'd like `mapOrThrow(CheckedFunction1<T,U>)` and `mapTry(Function1<T, Try<U>)` (needs better name) if possible.

As for `TryOptional`, I'm happy with not having it if possible - but I'd challenge "new types for every new use-case" in this instance. Java's general method declaration problems are null handling/dereferencing and checked/thrown exceptions.
i.e. returning `null` or `throw`ing exceptions are basic java constructs we'd like to avoid, and so having a specific type to do a non-nested generic conversion has some value.
e.g. `T foo() throws Bar { return null; }` could map to `TryOptional<T> foo()` instead of `Try<Optional<T>> foo()`.
On the other hand, I'm very happy with Java 8's generic inference - it's been able to do everything I want it to so far (with a bit of help with type definitions, but no casting).

**Comment by SimY4** [comment]
Having a look at it, do you think its a good idea to introduce `EitherT` and `OptionT` types to transform Eithers and Options inside any Value? Similar to what scalaz library provides.

So for example if you have a Future<Either<Exception, T>> you can wrap it in EitherT<Exception, T> and work the way you would work with regular Either. and then just extract the underlying Value.

**Comment by danieldietrich** [comment]
@skestle I've thought about it again. There must be a good reason to introduce new API because of the cost/benefit ratio.

We need clear entry/exit points between the standard Java API and the Vavr API. Leaking special standard Java API handling into the broad will unnecessarily complicate things and it does not scale well. There will be more questions like this to handle special cases and provide syntactic sugar. That is not the way it is supposed to be. We need a thin API (= few 'words') that is deep (= compositional).

Optional is designed to be used in conjunction with if. Therefore I suggest to use this solution to your problem:

```java
// Try<Option<R>>
Try.of(() -> retrieve(id)).mapTry(o -> o.isPresent() ? some(process(o.get())) : none());
```

I will close this issue (and my pull request #2101) and really hope you understand my decision.

@SimY4 Currently it is too much. Before adding more and more features in the broad I want to finish the 1.0.0 release. After that we can see if and how it fits into the library (in the presence of modules).
