### ISSUE TITLE
Why Function1 does not also extend PartialFunction?

### ISSUE THREAD

**Issue by endlessoblivion** [vavr-io/vavr#2153]
After reading [Integrating Partial Functions into Javaslang](http://blog.vavr.io/integrating-partial-functions-into-javaslang/), one possibility was left out uninspected: having `Function1` extend both `j.u.f.Function` and `PartialFunction`, like:

```java
interface Function1<T1, R> extends PartialFunction<T1, R>,
                                   java.util.function.Function<T1, R> {
    default boolean isDefinedAt(T1 value) {
        return true;
    }
}
```

Since total functions are a subset of partial functions, there should be no illegal use case. So is there any technical reason why `Function1` does not extend `PartialFunction`?

**Comment by danieldietrich** [comment]
Yes, it would be Variant 1 of the blog post but I think you mean that PartialFunction does not implement Function.

In Scala [PartialFunction extends Function1](http://www.scala-lang.org/api/2.12.3/scala/PartialFunction.html). This enables us to handle different cases:

```java
var sample = List.range(1, 4);
var isEven = Function1.of((Integer i) -> i + " is even").partial(i -> i % 2 == 0);
var isOdd = Function1.of((Integer i) -> i + " is odd").partial(i -> i % 2 == 1);

// = List("1 is odd", "2 is even", "3 is odd");
List<String> numbers = sample.map(isEven.orElse(isOdd));
```

where `sample.map takes a java.util.function.Function`.

On the one hand using partial functions in places where functions are expected is unsafe. On the other hand we would loose several use-cases for partial function.

---

For me, this is a signal that we do it wrong with partial functions. For Vavr 1.0.0 we should do the following:

* remove PartialFunction from io.vavr.core, especially Function1 should not depend on PartialFunction
* move PartialFunction to io.vavr.match because pattern matching is our only use-case for partial function (I think collect does not work at all)
* let PartialFunction stand on its own, it should not extend Function1 or j.u.Function

**Reason:** Scala has PartialFunction deeply integrated into the language (e.g. pattern matching and the `case` literal). We can't do that in Java. Trying to integrate it on our own seems artificial and it does not scale well regarding future versions of Java (which will come with native pattern matching).
