### ISSUE TITLE
Add {Optional,Try,...}#join

### ISSUE THREAD

**Issue by lslah** [vavr-io/vavr#2217]
Is there a reason why the monad classes don't have `join`-methods, like 
```java
static <T> Try<T> join(final Try<Try<T>> t) {
    t.flatMap(Function.identity());
}
```
You can obviously use `t.flatMap(Function.identity())` whenever you need `join`, but in some cases it would be handy and more readable to use `Try.join(t)`.
My specific situation is similar to this method:
```java
Try<T> get(CompletableFuture<Try<T>> future) {
    Try<Try<T>> result = Try.ofCallable(() -> future.get(timoutMs, TimeUnit.MILLISECONDS));
    return result.flatMap(Function.identity());
   // vs. return Try.join(result);
}
```
Maybe I am just missing another solution?

**Comment by danieldietrich** [comment]
Hi Islah,
thank you for your question.
We have thought about it to add [flatten](https://github.com/vavr-io/vavr/issues/1329)<sup>1)</sup> as static function to our types.
However, I think the benefit over `flatMap(t -> t)` isn't that great to make a good case for the extra maintenance aspect of static methods outside of the type hierarchy.
I hope you understand that we will not add it to the library.

Thanks for using Vavr!

\- Daniel

<sup>1) we prefer to align our names to Scala instead of Haskell</sup>

**Comment by lslah** [comment]
Hi Daniel,
thank you for your response.
I was sure there must have been some discussion about join/flatten but it didn't occur to me to search for flatten. Next time I'll check the scala names.

Thank you for vavr!
