### ISSUE TITLE
Function1.curried() differs from Function[2-8].curried() pattern

### ISSUE THREAD

**Issue by nfekete** [vavr-io/vavr#2240]
`Function1.curried()` differs from the rest of the `Function[2-8].curried()` implementations. I believe the correct signature and implementation for `Function1.curried()` should be:
```java
@Override
default Function1<T1, Function0<R>> curried() {
    return t1 -> () -> apply(t1);
}
```

**Comment by nfekete** [comment]
Also affects `CheckedFunction1.curried()`

**Comment by nfekete** [comment]
Well, it turns out we still can't make them totally consistent with each other without also changing `Function[2-8].curried()` in similar fashion from
```java
default Function1<T1, Function1<T2, R>> curried() {
    return t1 -> t2 -> apply(t1, t2);
}
```
to
```java
default Function1<T1, Function1<T2, Function0<R>>> curried() {
    return t1 -> t2 -> () -> apply(t1, t2);
}
```
Otherwise we would still be making `Function1.curried()` special in that it would be the only `curry()` function returning a chain ultimately resulting in `Function0`, while the rest of the `curry()` methods would ultimately result in `Function1`.

I feel the correct approach would be to make them absolutely consistent with each other.

What do you think, @danieldietrich ?

**Comment by danieldietrich** [comment]
@nfekete 

[Currying](https://en.wikipedia.org/wiki/Currying) is well-defined:

Given a function `f: (A x B) -> C`, the curried form is defined to be `curried(f): A -> (B -> C)`.

Scala does it this way for `Function2`:

<img width="654" alt="screen shot 2018-04-09 at 13 29 31" src="https://user-images.githubusercontent.com/743833/38495693-d3f6a470-3bfa-11e8-8bcf-c107d9f50621.png">

Unsurprisingly, it is not defined for `Function1`:

<img width="526" alt="screen shot 2018-04-09 at 13 28 40" src="https://user-images.githubusercontent.com/743833/38495730-f1d580d8-3bfa-11e8-9326-2bfaa7f1ac92.png">

---

We should removed `curried()`, `tupled()` and `reversed()` from `Function0` and `Function1`. They do nothing at all and exist only for academic reasons.

However, we could keep all as-is in order to stay backward compatible here.

---

**Note:** I would not re-open #2239. Using a lambda is easy enough `Function0<R> f0 = () -> f1.apply(t);`.

**Comment by nfekete** [comment]
Yes, I agree with keeping them for compatibility.

**Comment by danieldietrich** [comment]
Thank you, that is a good solution.
