### ISSUE TITLE
Why is Set a Function1?

### ISSUE THREAD

**Issue by Sir4ur0n** [vavr-io/vavr#2249]
I found out after spending several minutes on a compilation error in my code, that `Set` extends `Function1`. I see it has been done in #963 but I don't understand the rationale behind.

However I do see the problems it brings to the party for pattern matching:
```java
Set<String> abc = Set("abc");
Set<String> result = Match(abc).of( // Does not compile: the Java inference engine sees abc as a Function1<String, Boolean> before a Set<String> thus expects result to be of type Boolean
    Case($(), abc)
);
```

Even without considering this pattern matching issue, I think this doesn't make sense. A Set<T> is not a function taking a T and returning whether this Set contains it.
It is also not intuitive: I don't think many (any?) developers expect this.
Last: this looks like "favoritism" towards `io.vavr.collection.Set#contains` method. Why isn't `Set<T>` a `Function1<T, T>` in the name of `io.vavr.collection.Set#add`?

There's also no hint/explanation in the Javadoc.

**Comment by nfekete** [comment]
I agree... It's just too easy to create a function out of a `Set` with a method reference to the `contains` method. I think this could be handled while we're still in the pre 1.0 phase. Or in any phase, as it's quite easy to work around it. Same for `Seq`, `Map`, `Multimap`.
```java
Set<Integer> set = HashSet.of(1,2,3);
Function1<Integer, Boolean> f = Function1.of(set::contains);
```

**Comment by Sir4ur0n** [comment]
Should I submit a PR?

**Comment by danieldietrich** [comment]
@all 

We aligned to Scala, there Set extends (A) => Boolean:

<img width="907" alt="screen shot 2018-05-23 at 13 10 49" src="https://user-images.githubusercontent.com/743833/40421776-4a31f55e-5e8d-11e8-9468-c3be1c1cd078.png">

The same applies to Seq and Map and Multimap:

```java
public interface Seq<T> extends Traversable<T>, PartialFunction<Integer, T>, Serializable {
}

public interface Map<K, V> extends Traversable<Tuple2<K, V>>, PartialFunction<K, V>, Serializable {
}

public interface Multimap<K, V> extends Traversable<Tuple2<K, V>>, PartialFunction<K, Traversable<V>>, Serializable {
}
```

where PartialFunction extends Function1.

---

@Sir4ur0n 

However, the real problem are the Match.Case overloads. In our case the following are interesting:

```java
    @GwtIncompatible
    public static <T, R> Case<T, R> Case(Pattern0<T> pattern, Function<? super T, ? extends R> f) {
        Objects.requireNonNull(pattern, "pattern is null");
        Objects.requireNonNull(f, "f is null");
        return new Case0<>(pattern, f);
    }

    @GwtIncompatible
    public static <T, R> Case<T, R> Case(Pattern0<T> pattern, Supplier<? extends R> supplier) {
        Objects.requireNonNull(pattern, "pattern is null");
        Objects.requireNonNull(supplier, "supplier is null");
        return new Case0<>(pattern, ignored -> supplier.get());
    }

    @GwtIncompatible
    public static <T, R> Case<T, R> Case(Pattern0<T> pattern, R retVal) {
        Objects.requireNonNull(pattern, "pattern is null");
        return new Case0<>(pattern, ignored -> retVal);
    }
```

If we comment out `Case(Pattern0<T> pattern, Function<? super T, ? extends R> f)`, your initial code example compiles fine, because `Case<T, R> Case(Pattern0<T> pattern, R retVal)` is taken.

---

Method overloading in combination with inheritance leads to ambiguities. This is a weakness of our current API. We should think about our options to remove these potential ambiguities completely.

**Comment by Sir4ur0n** [comment]
I managed to find an example of why Scala's Set extends `(A) => Boolean`: https://alvinalexander.com/scala/how-use-scala-set-function-predicate

However I keep thinking this is not a good design, even in Scala. I feel like this is a time saver in 1% of the cases but misleading in 99% of the cases... As @nfekete pointed out, it's just so easy/cheap to write `contains` (either in Java or Scala) for these 1% that it doesn't seem relevant.

Overall using a Scala Set as a function seems to be nearly never used (or I didn't use the right terms with my friend Google).

I'm also not a good Scala developer: Scala may be handling overloading + inheritance just fine. However Java definitely doesn't.

Of course a solution is to NOT use overloading (different method names). I'm just afraid of ending with very long method names to describe each signature (CasePatternValue, CasePatternSupplier, CasePatternFunction), or worse, cryptic method names (CasePV, CasePS, CasePF) leading to overall less usability/affordance.

**Comment by danieldietrich** [comment]
I agree, Set as a Function is rarely used.

Having Seq, Map and Multimap being PartialFunctions is useful in the sense that they can be used in conjunction with the `Traversable.collect(PartialFunction)` method. There is no syntactic sugar in order to create PartialFunction instances, they are no FunctionalInterfaces.

However, PartialFunction extends Function ([like in Scala](https://www.scala-lang.org/api/2.12.2/scala/PartialFunction.html)). This leads to the same ambiguities we already experienced with Set.

We could remove

```java
public static <T, R> Case<T, R> Case(Pattern0<T> pattern, R retVal) {
    Objects.requireNonNull(pattern, "pattern is null");
    return new Case0<>(pattern, ignored -> retVal);
}
```

But then we wouldn't be able anymore to return constants using pattern matching, your initial example would look like this:

```java
Set<String> abc = Set("abc");
Set<String> result = Match(abc).of(
    Case($(), () => abc)
);
```

or like this:

```java
Set<String> abc = Set("abc");
Set<String> result = Match(abc).of(
    Case($(), set => set) // resp. Function.identity()
);
```

The question is, which functionality to remove:

* [ ] Set extends Function1, Seq/Map/Multimap extends PartialFunction
* [ ] Case(Pattern0&lt;T> pattern, R retVal)

🤔

**Comment by nfekete** [comment]
What if we would have `PartialFunction` defined as
```java
public interface PartialFunction<T, R> {
    Option<R> apply(T t);
    
    static <T, R> PartialFunction<T, R> of(PartialFunction<T, R> f) {
        return f;
    }
}
```
Then, creating a `PartialFunction` from a `Map` would be just
```java
Map<String, Integer> map = HashMap.of("a", 1, "b", 2, "c", 3);
PartialFunction<String, Integer> pf = PartialFunction.of(map::get);
```
I know, this would break the alignment with Scala. It would also incur one extra allocation of `Option<R>`, in case partial function is defined at that value, otherwise it will return the singleton `empty()`.

But calling `isDefinedAt` and possibly `apply` in `PartialFunction`'s current form has it's own cost: a double lookup in case of a `Map` for example. So we could argue which one is more efficient of the two. My off-the-cuff prediction would be that the allocation of `Option` would be the cheaper one as JVM is quite good at optimization, and escape analysis would make it possible to allocate these `Option` instances on the stack whenever it can make sure it doesn't escape the local context - but I admit, I haven't made any measurements on this.

**Comment by nfekete** [comment]
I've made some quick measurement testing with the current `PartialFunction` and the functional interface one that would return `Option`. You can see the JMH benchmark and the results at https://gist.github.com/nfekete/d671372ec8fb631308a495296b47326e

There are two runs, one with 100% hit ratio, the other with 50% hit ratio (all keys have entries in the map, half of the keys have entries in the map, by random).

Interestingly, the functional interface version that returns `Option` is both faster and lighter on the GC. It has around half the memory allocations (avg 64 bytes vs 32 bytes when run with 100% hit ratio) compared to the current version.

**Comment by danieldietrich** [comment]
@nfekete Thank you, that's interesting. If PartialFunction uses Option under the hood, **one use-case is missing**: We can't ask the PF anymore if it is defined for some input without calculating the output.

The Bit Mapped Trie (BMT) used by Map.get already calculates Option instances. Your new PF is constructed using a method reference, which performs better/has less overhead than a lambda instance. This leads to the benchmark results we observe.

The general case would be to have a domain, which is implemented in two independent ways, with PF_old and PF_new. I expect PF_new. Also both PF_old and PF_new have to be instantiated the same way (lambda vs method reference) to get a comparable benchmark.

---

Nevertheless, because of the uncovered use-case mentioned above I prefer to stay with the Scala-like PF. Also we keep our Case overloads (there exists a workaround using type-witnesses). We will remove  the {Set, Seq, Map, Multimap} extends [Function|PartialFunction].

We could then add conversion methods to cover the missing functionality:

```java
interface Set<T> {
    Function<T, Boolean> toFunction();
}

interface Seq<T> {
    PartialFunction<Integer, T> toPartialFunction();
}

interface Map<K, V> {
    PartialFunction<K, V> toPartialFunction();
}

interface Multimap<K, V> {
    PartialFunction<K, Traversable<V>> toPartialFunction();
}
```

Additionally Seq and Map have methods `withDefault` which make the PartialFunctions total. (Interestingly Multimap does not have these methods). We should move (and rename) the `withDefault` methods to `PartialFunction:

```java
interface PartialFunction<T, R> extends Function1<T, R> {

    default Function1<T, R> total(R defaultValue) { ... }

    default Function1<T, R> total(Function<? super T, ? extends R> defaultFunction) { ... }

}
```

**Comment by hepin1989** [comment]
The same question is just asked on scala's gitter:)
> Map#apply looks up the key and returns the value (or throws an exception if not found)

**Comment by danieldietrich** [comment]
@chisui you are right. It had historic reasons, we aligned to Scala. However, newer version of Scala also removed the Function type from Set:

<img width="851" alt="Screenshot 2020-08-06 at 22 54 53" src="https://user-images.githubusercontent.com/743833/89581967-20e70280-d838-11ea-921e-f5caf907fd4d.png">

Let's do it and also remove it!
Any volunteers for a PR?
