### ISSUE TITLE
toList from iterator is little to specific

### ISSUE THREAD

**Issue by rajneeshg0** [vavr-io/vavr#2253]
I think return type of toList on Iterator require you match the variable to be of List type. Generally I would expect it to be able to return higher type like Seq so that anyone can change the implementation for the custom iterator to his own types instead of limited to List. Other more compelling reason is I think is that Iterator is more generic interface not tied to any specific implementation of Seq. 
At the minimum I think iterator should have toSeq method as well.

This is the idea  almost in all interfaces in java  e,g stream.collect

**Comment by danieldietrich** [comment]
Thank you, I will take it into account when modularizing Vavr 1.0. The _specific_ conversion methods will disappear or replaced by a generic conversion method, like

```java
<C extends Traversable<T>, T> to(Class<C> type)
```

**Comment by nfekete** [comment]
`to(Class<C> type)` seems a bit ugly to me as it involves reflection to create an instance of that class. Isn't `Value.collect()` enough for this?

**Comment by danieldietrich** [comment]
@nfekete yes, nice suggestion! In the case of Traversables `Value.collect()` is sufficient.

I had a more general conversion method in mind that also works for the single-valued `Value` implementation (like Option, Try, ...). Driver is modularization. Once we split modules, the base module `io.vavr.core` will not depend on collections, controls etc. anymore. Then the specific `toOption()`, `toTry()`, etc. methods will disappear.

However, when looking at `Value` I think, I will remove it completely. Without the conversion methods, there will not be much that remains:

```java
 * Basic operations:
 *
 * <ul>
 * <li>{@link #get()}</li>
 * <li>{@link #getOrElse(Object)}</li>
 * <li>{@link #getOrElse(Supplier)}</li>
 * <li>{@link #getOrElseThrow(Supplier)}</li>
 * <li>{@link #getOrElseTry(CheckedFunction0)}</li>
 * <li>{@link #getOrNull()}</li>
 * <li>{@link #map(Function)}</li>
 * <li>{@link #stringPrefix()}</li>
 * </ul>
 *
 * Equality checks:
 *
 * <ul>
 * <li>{@link #corresponds(Iterable, BiPredicate)}</li>
 * <li>{@link #eq(Object)}</li>
 * </ul>
 *
 * Iterable extensions:
 *
 * <ul>
 * <li>{@link #contains(Object)}</li>
 * <li>{@link #exists(Predicate)}</li>
 * <li>{@link #forAll(Predicate)}</li>
 * <li>{@link #forEach(Consumer)}</li>
 * <li>{@link #iterator()}</li>
 * </ul>
 *
 * Side-effects:
 *
 * <ul>
 * <li>{@link #out(PrintStream)}</li>
 * <li>{@link #out(PrintWriter)}</li>
 * <li>{@link #peek(Consumer)}</li>
 * <li>{@link #stderr()}</li>
 * <li>{@link #stdout()}</li>
 * </ul>
 *
 * Tests:
 *
 * <ul>
 * <li>{@link #isAsync()}</li>
 * <li>{@link #isEmpty()}</li>
 * <li>{@link #isLazy()}</li>
 * <li>{@link #isSingleValued()}</li>
 * </ul>
```

* The `getXxx()` methods will be revisited (Vavr vs. Java vs. Scala), removed from the Traversables and moved to Option, Try, ...
* `map`-only makes no sense without `flatMap`, which is not possible in Java. Namely, we are not able to abstract over Monads towards For-Comprehensions. In Java we have to implement it for each type separately (using method overloads). See `API.For`, #1629, #2216
* `stringPrefix()` is (more or less) the same as `getClass().getSimpleName()`. I will remove it from Vavr 1.0.
* Equality checks `corresponds` and `eq` were a mistake. We don't need yet another notion for equality in Java. With the upcoming native Java _value types_ we will get deep quality.
* we don't really need _Iterable extensions_ for single-valued types. There are workarounds. Some methods might be moved to Traversable. Most Vavr types will extend Iterable directly.
* All side-effects (but peek()) will be removed. These are basically console outputs.
* The tests are not needed IMO. Characteristics should be made explicit by using the according types, i.e. Iterator or Stream for the lazy case, Future for the async case, etc. Of course isEmpty() is still needed.

---

Regarding the conversion method for single-valued types, we need 'another layer of indirection' in order to make types convertible. More specifically, we need to be able to access the state of a monad somehow.

**Examples:**

| this | to | result |
| --- | --- | --- |
| Some(t) | Try | Success(t) |
| None | Try | Failure(NoSuchElementException) |
| Some(t) | Future | Future(Success(t)) |
| None | Future | Future(Failure(NoSuchElementException)) |
| Some(t) | Either | Right(t) |
| None | Either | _Left(Void)_ ? |
| Some(t) | Validation | Valid(t) |
| None | Validation | _Invalid(Void)_ ? |

We need also convert Try, Future, Either and Validation to all other types.

All these types have in common that they have dual states and all operations are biased to one of the states. We could solve the conversion issue by adding an interface `Convertible<T, U>` that is able to check the state and pull out one of the two values (according to the state).

What we need is a type constructor. We could build one the following way:

```java
public interface Try<T> extends Convertible<T, Throwable> {

    static <T, U> Try<T> cons(Convertible<T, U> convertible) {
        if (convertible instanceof Try) {
            return (Try<T>) convertible;
        } else {
            return convertible.isDefined() ? Try.success(convertible.get()) : Try.failure(new NoSuchElementException());
        }
    }
}
```

However, we would not be able to preserve specific state, like an exception when we convert an Either to a Try.

But maybe we don't need these conversions at all. Maybe we should convert in a first step

* Option &lt;-> Try
* Either &lt;-> Validation

...and that's it.

**Comment by danieldietrich** [comment]
We align to Scala. Additionally to Java's `collect(Collector)`, our collections will also have the `toXxx()` methods.

When redesigning Iterator for 1.0, we will align to Scala...

```scala
scala> val i: Iterator[Int] = Set(1, 2, 3).iterator
i: Iterator[Int] = <iterator>

scala> i.toList
res1: List[Int] = List(1, 2, 3)

scala> i.toSeq
res2: Seq[Int] = List()
```

**Comment by danieldietrich** [comment]
On help let's discuss it first.

**Comment by pivovarit** [comment]
Since the `Iterator# List toList()` is already present, the actual alignment would involve just the addition of `toSeq` methods on `Iterator`?

**Comment by danieldietrich** [comment]
@pivovarit Hold your horses. I'm not sure about that. I will come back in 1 hour...

**Comment by danieldietrich** [comment]
@pivovarit Let's only cover `toSeq` in this issue.

In Scala, a List implementation is returned by toSeq. (I thought it would be Vector because it is general purpose but List is more efficient for few elements).

<img width="346" alt="Screenshot 2019-12-13 at 19 50 14" src="https://user-images.githubusercontent.com/743833/70824195-fe543500-1de1-11ea-965b-e80112659b0e.png">

If we decide to add other methods, like toSet, we will create separate PRs...
