### ISSUE TITLE
Option .map should probably gracefully handle Functions that return null.

### ISSUE THREAD

**Issue by chantrybjss** [vavr-io/vavr#2260]
See the source below.

```
default <U> Option<U> map(Function<? super T, ? extends U> mapper) {
    Objects.requireNonNull(mapper, "mapper is null");
    return this.isEmpty() ? none() : some(mapper.apply(this.get()));
}
```

If the mapper can potentially return nulls, this will cause a Some to be created with a null value. This prevents chaining such as Option.of(someObj).map(someFunctional).map(someOtherFunctional). 

I know Option is not meant to mimic Java's implementation, but I feel the Optional has this right.

**Comment by danieldietrich** [comment]
Hi @chantrybjss,

thank you, that is one of the most controversial discussed topics regarding Vavr.

Vavr was originally designed to bring some of the Scala goodness to the Java world, including Option’s semantics. Today, after developing Vavr for more than 4 years, I would handle things a little different.

In the first place, a library that extends an existing language, **must not duplicate features**, especially when using different semantics (like Vavr does with Option).

Second, similar features, like Try, Either, ..., **should align to existing native API’s** (like Optional) in order to not confuse developers.

I already thought about changing Vavr by completely removing Option and align the Try API to the one of Optional. What would we loose?

The main features of Vavr’s Option are

* it is iterable
* it is serializable
* it is convertible within the Vavr space

Convertability currently does not scale very well because of tight coupling. This is a solvable problem.

I give nothing about so-called serializability. Sending objects through a wire can be achieved without extending Serializable.

The most important aspect (of all Vavr _values_) is that they are iterable. It enables us to compose things in a gereric way.

—-

What is your main reason to use Vavr’s Option. Could you also use Optional? What hinders you/what would it take to increase interoperability between Vavr and Java’s Optional?

Thx!

**Comment by chantrybjss** [comment]
In this case, I have actually reverted to using Optional in my code.

My main concern is that the map method allows Option to create a Some with a null value, which I had  assumed would be impossible. 

I have looked closer at the code and it appears map is not unique in this respect. I had assumed some() was a private scoped method, but it is actually possible to create Some objects of null type (seemingly by design). 

It is my opinion that it should not be possible to create null valued Some objects. However, I do not want to get into a debate about API design, so unless there is some other reason, I think it is safe to close this issue.

**Comment by nfekete** [comment]
@chantrybjss as a workaround you could use this pattern:
```java
option.map(nullReturningFunction).flatMap(Option::of)
```
The `flatMap(Option::of)` would make sure you switch over from `Some(null)` to `None`.

**Comment by chronodm** [comment]
I think there are subtle philosophical differences between `Optional` and `Option`. `Optional` starts from a universe of null pointers and tries to make it easier for functional programming to operate in that universe. `Option` starts from a universe of functional constructs and includes a bridge (`Option.of`) to get data out of that other universe.  

Vavr-native code shouldn't use `null`, and if you're talking to a non-Vavr-native library that's documented to return nulls (such as `java.util.collection`), Vavr's design encourages you to wrap it in `Options`; but `Option` isn't _intended_ as a mechanism to prevent `NullPointerExceptions`.

The way to think about nullable code, I think, is a bit like `unsafe` in [C#](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/unsafe-code-pointers/index) or [Rust](https://doc.rust-lang.org/book/second-edition/ch19-01-unsafe-rust.html)—don't spend any more time there than you have to, be careful when you do and don’t let the nulls escape into your “safe” core code.

Some day, maybe `@Nullable` will be standardized and enforcable and magically applied to the whole compilation scope by static analysis, but until then, as they say in Python, “[explicit is better than implicit](https://www.python.org/dev/peps/pep-0020/)”. If you forget the `Option.of` call, that's a programming error that should [fail fast](https://www.martinfowler.com/ieeeSoftware/failFast.pdf).

**Comment by chronodm** [comment]
(P.S. Some interesting discussion of the [history of Optional here](https://www.voxxed.com/2015/06/reasons-to-be-cautious-with-optional/), including links to mailing list archives where you can dig into the fights over why it doesn't behave like [various other `Option` implementations and `Option`-like things that all behave differently from one another]. If you want to go down that rathole, the [Loose Ends: Optional](http://mail.openjdk.java.net/pipermail/lambda-libs-spec-experts/2013-June/001864.html) thread is particularly interesting.)

**Comment by danieldietrich** [comment]
Some features that are possible because of our Option implementation:

* Our `Map` supports `null` keys and values. I.e. `map.get(k)` may return `Some(null)` if the k is associated with null, and `None` if no value is associated with k.
* Symmetrie: option.toTry().toOption() = option (works for both, Some and None)

That's how things should work. My experience is that other interpretations are eligible but not canonical.

**Comment by sievemaker** [comment]
> Some features that are possible because of our Option implementation:
> 
> * Our `Map` supports `null` keys and values. I.e. `map.get(k)` may return `Some(null)` if the k is associated with null, and `None` if no value is associated with k.
> * Symmetrie: option.toTry().toOption() = option (works for both, Some and None)
> 
> That's how things should work. My experience is that other interpretations are eligible but not canonical.

This example with Map makes sense, however getting Some(null) is not very useful, is it? Maybe in both cases we should get None, or we should have possibility to implicitly convert from Some(null) to None() if we want it?!

**Comment by ezoerner** [comment]
There are blogs written about this, Some(null) must be possible in order for Option to obey the functor laws.  It is java's `Optional` that is broken—Scala and vavr got it right.
