### ISSUE TITLE
TreeMap/SortedMap last/max won't use custom comparator

### ISSUE THREAD

**Issue by jorgepelizzoni** [vavr-io/vavr#2299]
Hi there :)

First of all I'd like to compliment you on your great work! Regarding the issue: currently last/max for TreeMap/SortedMap and possibly other types/operations will always rely on natural order, which got me to a rather nasty bug today. What about having something like this in Traversable:

```
default Comparator<T> getImplicitComparator() {
        return this instanceof Ordered ? ((Ordered<T>) this).comparator() : Comparators.naturalComparator();       
}

default Option<T> max() {
        return maxBy(getImplicitComparator());
}
```

Thanks in advance. Cheers,

Jorge.

**Comment by danieldietrich** [comment]
Hi @jorgepelizzoni, thank you for the kind words.
It is a known issue that Comparators are not used consistently on sorted collections, see #1226 and #1391.
Var 0.9.x can't be fixed in a backward-compatible way, it would break existing applications.
So I will defer the Comparator-related changes to Vavr 1.0.

I will close this issue as duplicate.

---

A few notes regarding your suggestion: Instead of adding new methods, we will update the API docs of max() (by stating a different behavior, depending of the collection type). Generally, we will remove most default method implementations on interfaces and move them into the concrete classes. This is because we do not want to implicitly depend on specific implementation types within our interfaces. That is a fragile construct. For example users could decide to implement their own collection based on Vavr interfaces, that uses an internal Comparator but does not implement Ordered. Then things would start to go terribly wrong.

Thanks again!

**Comment by danieldietrich** [comment]
@jorgepelizzoni I will double-check the behavior when comparing it to Scala collections.
