### ISSUE TITLE
LinkedHashMap#put has O(n) complexity but documentation states it is O(1)

### ISSUE THREAD

**Issue by yuriykulikov** [vavr-io/vavr#2343]
In case if the Map already has the given key, LinkedHashMap#put complexity becomes O(n).
The documentation states it is O(1) - http://www.vavr.io/vavr-docs/#_collections

Remove also has O(n) complexity.

For reference, java.util.LinkedHashMap#put has O(1) complexity.

See also the discussion here: https://github.com/vavr-io/vavr/issues/1838

Either the documentation should be adjusted of the implemention should be changed to actually be O(1).  This, of course, would involve major changes, because both queues must be changed in O(n).

**Comment by nfekete** [comment]
Scala has a data structure with similar behavioral but weaker runtime guarantees: [`ListMap`](https://www.scala-lang.org/api/current/scala/collection/immutable/ListMap.html)

**Comment by yuriykulikov** [comment]
Immutable LinkedHashMap can be implemenented, but I do not think that a persistent collection can be used for the list. Unlinke mutable linked lists, which can be unlinked/relinked in O(1) if we have a reference to the node, immutable linked lists cannot be updated in the middle without rebuilding the whole structure after the insertion point. So basically, to achieve O(1) we need a persistent data structure, which can be updated in O(1) and I do not know any :)

**Comment by danieldietrich** [comment]
@yuriykulikov Vector is effectively O(1), because of the high branching factor of the underlying tree structure. A List fits good for few elements, Vector scales better when the number of elements gets bigger.

Currently LinkedHashMap internally maintains two data structures, one for the Map _(currently HAMT based, in a future impl maybe CHAMP based, like in the upcoming Scala 2.13)_, and one for the order of elements. I think there is room for improvement, maybe a dedicated/optimized low-level data structure.

**Comment by yuriykulikov** [comment]
BTW, Kotlin persistent collections have O(log(n)) for put.

**Comment by danieldietrich** [comment]
I know, there is still plenty of room for improvement. Mid-term, I would love to see Scala 3 collection impls here (e.g. Champ).
