### ISSUE TITLE
Possibility to rerun failed execution in Try

### ISSUE THREAD

**Issue by slawekjaranowski** [vavr-io/vavr#2385]
According to comment in PR #2384 I will discuss how to retry failed execution.

My proposition is add `retry` method in `Try`, but this extends Scala's Try implementation.

In my proposition we can simply write:

    Try.of(() -> restClient.call()).retry(5, 5, TimeUnit.SECONDS)

**Comment by thadumi** [comment]
Hi, what about a new Try type, maybe UrgentTry. This because if I could use retry I'd like to have the possibility to do something every time the Try fails, for example for debugging purposes, and also methods which let me know how many time it tried to achieve the success. 
So my code idea is 
```
Try.of(() -> restClient.call())
     .onFailure(t -> somthingWhenAnAttemptFailed(t))
     .retry(5, 5, TimeUnit.SECONDS) //lhere the Try is lift to UrgentTry
     .onFailure( (t, count) -> somthingWhenTheNthAttemptFailed(t, count))
     .onFinalFailure(t -> allTheAttemptsFailed(t))
```

We could also have this 
 .onFailure( (urgentTry, t, count) -> {
    somthingWhenTheNthAttemptFailed(t, count);
    boolean shouldTryAgain = ...;
   if(shouldTryAgain) urgentTry.censure();
   else urgentTry.keepTheFailState();
})

**Comment by danieldietrich** [comment]
I do not plan to implement retry logic in Vavr. We once had `javaslang-circuit-breaker`, which was externalized then and renamed to [resilence4j](https://github.com/resilience4j/resilience4j).

I tag this issue as 'question'. Let's brainstorm / examine here, how Vavr could be combined with other libraries in order to achieve retry logic.
