### ISSUE TITLE
Does VAVR need Try.ofNullable?

### ISSUE THREAD

**Issue by danwallach** [vavr-io/vavr#2392]
`Option.of(null)` returns `none()`, but `Try.of(() -> null)` returns `success(null)`. There are a number of libraries out there which return `null` to indicate some sort of error condition.

_Suggestion_: Something like this in the standard `Try` class:

```java
static <T> Try<T> tryOfNullable(CheckedFunction0<? extends T> supplier) {
    return Try.narrow(
        Try.of(supplier)
            .filter(
                Objects::nonNull,
                () -> new NullPointerException("expected non-null result from supplier")));
  }
```

A more interesting philosophical question is whether `success(null)` should be a thing, or whether `success(null)` should actually be `failure(new NullPointerException(...))`.

**Comment by danieldietrich** [comment]
Null is semantically used in a thousand ways by other libraries. Treat it as some sort of error is only one interpretation.

As a library developer I need to be open to all use-cases. Null resp. non-null is solely the domain of Option. Try's domain is error handling. The only commonality between Option and Try is that they are sum-types and monadic containers that obey specific laws.

There is nothing wrong with allowing null as resulting value of a Try. Scala does the same:

<img width="824" alt="Screenshot 2019-03-23 at 22 33 46" src="https://user-images.githubusercontent.com/743833/54871922-5f535d00-4dbc-11e9-923a-e1483a91c437.png">

**Comment by danwallach** [comment]
Fair enough, but it would still be handy to have `Try.ofNullable()` or equivalent.

**Comment by danwallach** [comment]
Meanwhile, the following test passes. This seems problematic:
```java
Try<String> ts = Try.of(() -> null);
Option<String> os = ts.toOption();
Option<String> ns = Option.of(null);

assertTrue(ts.isSuccess());
assertTrue(os.isDefined());
assertFalse(ns.isDefined());
assertNull(os.get());
assertNull(ts.get());
assertThrows(NoSuchElementException.class, () -> { var ignored = ns.get(); });
```

**Comment by danieldietrich** [comment]
Yes, allowing null on the sunny path of a monad always has been a two-edged sword, not only in the presence of conversion between monadic containers. Allowing null is essential in order to obey the monad laws. Java's Optional breaks monad laws in order to handle null special.

Examples:

```java
// Scala, VAVR
Some(1).map(i -> null) // = Some(null)

// Java
Optional.of(1).map(i -> null) // = empty Optional
```

We know that this happens and think that this is the right way to do it. There has been a lot of discussion in the past. Essentially, breaking the monad laws would introduce unexpected behavior when using compositional constructs based on the monad laws, like for-comprehensions (because associativity has to be fulfilled).
