### ISSUE TITLE
java process runs for some time when i execute the below code though the code completes execution.

### ISSUE THREAD

**Issue by FuncGuy** [vavr-io/vavr#2412]
```java
Future<Object> future = Future.of(() -> 5/0)
    .transformValue(result -> Try.of(() -> result.get())
        .recoverWith(ArithmeticException.class, Try.of(() -> 2/0)
            .recoverWith(ArithmeticException.class, Try.of(() -> 4/0)
                .andFinallyTry(() -> System.out.println("Lost all attempts!!!")))));
```

**Comment by danieldietrich** [comment]
It might be related to the underlying (default) ExecutorService of the Furure. Which version of VAVR do you use? Did you try the latest 0.10.0?

**Comment by danieldietrich** [comment]
I think you do not use the newest version of VAVR (it is 0.10 and 1.0 will be released soon).

Your example runs in 86 ms on my machine (including unit test framework utilization etc.). The JVM exists immediately.

<img width="1618" alt="Screenshot 2019-07-05 at 00 26 46" src="https://user-images.githubusercontent.com/743833/60689267-cd2f1a80-9ebb-11e9-8dcc-535979d9dbb0.png">

It is like I said before: I think you use an outdated version of VAVR that had a different default ExecutorService that needed some time to release pooled Executors. Now we use ForkJoinPool.commonPool() that behaves different.

You might want to use the following code snippet in order to prevent your JVM to exit before pending threads finished:

```java
    static void gracefullyFinishThreads() throws TimeoutException {
        final boolean isQuiescent = ForkJoinPool.commonPool().awaitQuiescence(1L, TimeUnit.MINUTES);
        if (isQuiescent) {
            System.out.println("ForkJoinPool.commonPool() is quiecent");
        } else {
            throw new TimeoutException("Timeout while waiting for running threads in ForkJoinPool.commonPool() to finish.");
        }
    }
```

Please choose an appropriate time span (here I use 1 minute, which might be too long).
