### ISSUE TITLE
Add getOption() to Seq

### ISSUE THREAD

**Issue by JakobBruenker** [vavr-io/vavr#2505]
`Seq` has `get(int index)`, however, this is a partial function which throws an exception if the `index` is out of bonds.

As far as I can tell, there is no total function that allows you to get a specific element out of a sequence, returning an optional result. This is a method that is widespread in other contexts, for example, multiple Haskell packages have a function `(!?)` which does exactly that.

Given other method pairs like `init()` and `initOption()`, `getOption(int index)` seems like a natural inclusion to the `Seq` interface, which I found myself missing when using vavr `Array`s.

**Comment by nfekete** [comment]
I thought about this for a little bit, and given that these collections are immutable, it's usually a programming error to try and get an element with an index that is out of range. 

In this regard this would be different from `headOption()` and `lastOption()` as those are more like saying _give me the first/last element if the collection is not empty, otherwise return None_, and it's usefulness lies in that you can `orElse(...)` on it right away, as a way to provide a default value for the case when the collection was empty.

But is there a valid use case where we would like to say: _give me the 5th element if the collection is at least 5 elements long, otherwise return None_? Do you have other use cases that I don't see? One such use case that I could think of is to get rid of a range check when using user-provided indices.

Anyway, I kind of like the idea that the programmer can choose to trade a little bit of efficiency for more readable code, and getting rid of a range check is one of those cases. It can also fit much more naturally into another transformation pipeline, where you can just `flatMap` from practically any vavr `Traversable` to an `Option` returned by this new method (`Option` being an `Iterable`), so you can have a cleaner flow without the clutter of a range check.

**Comment by JakobBruenker** [comment]
> it's usually a programming error to try and get an element with an index that is out of range.

That might be true, but using `getOption(n)` rather than a range check for n + `get(n)` makes it a little bit less likely that a programmer will make a programming error, because now `n` is only used once. I think that by itself could be an argument in its favor.

User-provided sequences have similar use-cases to user-provided indices - for example, in a case where user supplies a `.csv` file in which rows can have either 3 or 4 elements, you could use getOption(3).

**Comment by danieldietrich** [comment]
We align to Scala (which does not have getOption) and already provide `lift()` for that purpose:

https://javadoc.io/doc/io.vavr/vavr/0.10.2/index.html

Therefore I will close this issue
