### ISSUE TITLE
consumer with n elements

### ISSUE THREAD

**Issue by keremyzc** [vavr-io/vavr#2509]
is there an easy way to represent a ```Consumer3``` with n elements?

just an example;
```
Consumer3<Id, Time, Meta> logMeta = (id, time, meta) -> LOGGER.info("id:{} execution took:{} ms, meta:{}", id, time, meta) 
```

**Comment by danieldietrich** [comment]
We need to wait for [JEP 218: Generics over Primitive Types](https://openjdk.java.net/jeps/218). Then we will be able to express all kind of functions using Vavr's Function1..8.

In this case:

```java
Function3<T1, T2, T3, void> triConsumer = (t1, t2, t3) -> { /* perform side-effects */ };
```

Until then you have to create your own functional interface. I think the Java language architects think that's the proper way to do it in Java: choosing meaningful names for your functional interfaces instead of using general purpose ones.

**Comment by keremyzc** [comment]
Thanks Daniel, make sense, that's exactly what I did for now.
