### ISSUE TITLE
Convenient Option flatmap null handling

### ISSUE THREAD

**Issue by chrylis** [vavr-io/vavr#2517]
I understand the basis for requiring a `flatMap` to transform a potentially null-returning function on an `Option` value, but the current API (0.10.2 and 1.0.0-a3) is exceedingly clumsy to use, when in most realistic cases a `Function<T, @Nullable U>` is available. This leads to boilerplate like this:

```
private static <T, U> Function<? super T, Option<? extends U>> maybeNull(Function<? super T, ? extends U> wrapped) {
    return (input) -> Option.of(wrapped.apply(input));
}
```

It would be significantly convenient to have a method called something like `flatMapUsing`, analogous to `mapTry`, that implemented the `Optional#map` behavior:

```
default <U> Option<U> flatMapUsing(Function mapper) {
  return isEmpty() ? none() : Option.of(mapper.apply(get()));
}
```

**Comment by danieldietrich** [comment]
Our strategic design decision is to keep the API surface area small. We prefer composability over syntactic additions / syntactic sugar. Another design goal of Vavr is to align to the Scala standard library. If the method isn't there, we also will not introduce it most probably (module type system tweaks in Java).

**Comment by chrylis** [comment]
Why the discrepancy between `Optional` and `Try` in this case?

**Comment by danieldietrich** [comment]
Vavr aligns tightly to Scala because Scala evolved over years and is well thought through. Java's API seems artificial. Take a look at `java.util.Optional.of(T)` for example, which throws if the argument is null.

Regarding your question: yes, indeed, `mapTry` is an extra method that should not be part of our API. We added it because of a problem introduced by inheritance. Try, Option and Either extend Value. Value has `map(Function)`. Because Java does have checked exceptions, we couldn't simply overwrite `Value.map(Function)` with `Try.map(CheckedFunction)`. As a workaround, we added `Try.mapTry(CheckedFunction)`.

Btw - we already solved that problem. As part of Vavr 1.0.0, we deprecated `Value`. The new type at the top of the Vavr hierarchy will be ìo.vavr.Iterable`, which only has one abstract method: it overloads `iterator()` by returning Vavr's rich Iterator.

That way Try may define its own method `map(CheckedFunction)` and we are able to remove `mapTry`. This is the best we can do in Java.

We had to find similar workarounds in some types of our collections. The reason is that Java's type system is relatively simple and we library developers are very restricted in what can be expressed on the type level.

I hope this helps a bit.

Thx!
