### ISSUE TITLE
.copy(...) -- feature request

### ISSUE THREAD

**Issue by marcuslange** [vavr-io/vavr#2529]
I'm wondering if you will add a copy method similar to Scala and Kotlin. One of my biggest frustrations with immutability in java is not being able to clone a value object with a couple of changed params.

**Comment by danieldietrich** [comment]
Hi Marcus, thanks for your question!

Yeah, Vavr's types are immutable but luckily we provide many methods to transform the current state (read: the values) of a container type (mostly monads).

What you mean are for example the case classes in Scala. There is no equivalent concept in Java 8..13. However, Java will have so called _record_ types, which are similar to Scala's case classes.

I don't think there will be copy methods as part of Java records because you would need default parameters for that purpose:

```java
record Person(String name, int age) {
    // !!! non-existing phantasy API for default parameters !!!
    Person copy(String name = this.name, int age = this.age) {
        return new Person(name, age);
    }
}
```

As a workaround, you will be able to _deconstruct_ Java [Records](https://openjdk.java.net/jeps/359) using switch expressions:

```java
var person = new Person("Daniel", 0x2C);

var copy = switch(person) {
    case Person(var name, var age) -> new Person(name.toUpperCase(), age + 1);
};
```

I hope this helps!

Thx

Daniel
