### ISSUE TITLE
add shortcut methods to Match API

### ISSUE THREAD

**Issue by bruto0** [vavr-io/vavr#2570]
e.g.
```
    public static <T, R> Option<R> MatchOpt(T t, Case<? extends T, ? extends R>... cases) {
        return Match(t).option(cases);
    }
    public static <T, R> Option<R> Match(T t, Case<? extends T, ? extends R>... cases) {
        return Match(t).of(cases);
    }

```
This would allow to reduce the number of unnecessary names in resulting expressions

also this:
```
    public static <T, R> Case<T, R> Default(R retVal) {
        return Case($(), retVal);
    }
```
would be a more familiar alternative to MatchOpt(...).getOrElse(...)

**Comment by danieldietrich** [comment]
Hi @bruto0, thank you for your suggestion.

I thought about it but it does not align well to our strategy of keeping the API surface area small. This is really essential to keep the library simple and offer a great UX.

I understand that it is tempting to add syntactic sugar. But in the past, it showed that it will often not cover every use-case. Adding syntactic sugar does open the door for adding more syntactic sugar. At least there is no argument anymore to not add it. For example:

* Default(R)
* Default(Supplier&lt;R>)
* Default(Function&lt;T, R>)
* etc.

In the end, the API looks bloated. It already does in my opinion because many features are based on internal DSLs. I prefer to offer one canonical way to do things. Composition is a powerful tool that covers many use-cases.

I hope you understand it.

Thanks!

Daniel
