### ISSUE TITLE
Replacements lambda -> method references

### ISSUE THREAD

**Issue by strkkk** [vavr-io/vavr#2600]
Hi everyone, last time in issue https://github.com/vavr-io/vavr/issues/2445 you have provided valuable feedback about new checkstyle check that should detect lambdas that can be replaced with method references.
I have made some changes and wanted to ask your feedback for new version of check.
Report of detected violations (20) in project with default check configuration (only simple cases):
https://strkkk.github.io/checkstyle/120_vavr_default/Vavr/index.html

And this is the report with non-default config, with extended check for expressions, there are 29 additional violations.
https://strkkk.github.io/checkstyle/120_vavr_extended/Vavr/index.html

There is also report with both configs
https://strkkk.github.io/checkstyle/120/Vavr/index.html

Any feedback is appreciated.

**Comment by danieldietrich** [comment]
I checked your non-default report. We don't care about our tests. It makes (almost) no difference if you use lambdas instead of method references there. The code isn't released.

If we filter out the *Test classes, only 3 classes remain:

* `Function0`, `CheckedFunction0` - Could you please say, what you suggest to improve? All IntelliJ checks are fine with the code. I also can't see any possibility to improve it.
* `Tree` - will be moved to a different repo in Vavr 1.0

Thanks

**Comment by danieldietrich** [comment]
Personally, I prefer lambdas over method references from the _readability_ perspective.

**Example:**

```java
Try.<R>of<looooooooooooooong-time-nothing>::<argbitrary-method>
```

Pros:

* method reference slightly better handled by the JVM

Cons:

* The user needs to read the whole expression until it is clear that there hides somewhere a method reference `'::'`.
* the lambda type is not clear because the arguments are _hidden_ in the method declaration of the method reference.

When I see a code snippet

```java
() -> <something>
```

It is immediately clear to me that there is a function with no arguments, namely a `Supplier`.

---

The **readability** is slightly more important for our **tests**.

**Performance** is more important for **library code**.

---

I prefer to keep our code as is. I see only two findings in `(Checked)Function0` that would change semantics (laziness) if we change them. Therefore we will keep it as is.
