### ISSUE TITLE
Try.withResources() with Consumer

### ISSUE THREAD

**Issue by dlsrb6342** [vavr-io/vavr#2610]
It would be nice that can use `Try.withResources()` with `Consumer`.
But now, `Try.withResources()` only has `of(CheckedFunction1<? super T1, ? extends R> f)`.
What do you think adding `ofConsumer(CheckedConsumer<? super T1> consumer)`?

```java
File file = new File(absoluteFilePath);
Try.withResources(() -> new FileWriter(file, false))
   .of(writer -> {
       writer.write(contents);
       return true;
   }).getOrElseThrow(t -> new RuntimeException(String.format("File overwrite failed. path: %s", file), t));

// above code can be changed like following
File file = new File(absoluteFilePath);
Try.withResources(() -> new FileWriter(file, false))
   .ofConsumer(writer -> {
       writer.write(contents);
   }).getOrElseThrow(t -> new RuntimeException(String.format("File overwrite failed. path: %s", file), t));

```

**Comment by danieldietrich** [comment]
Hi @dlsrb6342, I'm afraid, we will drop the `Try.withResources` API in Vavr 1.0.

The migration path is to use native try-with-resources blocks within Vavr's Try.

You already can do it! Please write your example like this:

```java
File file = new File(absoluteFilePath);
Try.run(() -> {
  try (FileWriter writer = new FileWriter(file, false)) {
    writer.write(contents);
  }
}).getOrElseThrow(t -> new RuntimeException(String.format("File overwrite failed. path: %s", file), t));
```

The `Try.withResources` method overloads introduced

1. unnecessary runtime overhead (additional objects got instantiated because of the fluent API)
2. unnecessary big API surface area

The suggested approach outlined above has a smaller footprint and it is still easy to use. No additional vocabulary is needed, it is native Java notion.

I hope you understand our design decision.

Thanks for using Vavr!

\- Daniel
