### ISSUE TITLE
[Feature] Try forMap

### ISSUE THREAD

**Issue by xenoterracide** [vavr-io/vavr#2619]
I've got this code

```java
      Files.list(configDir)
        .filter( Files::isRegularFile )
        .filter( Files::isReadable )
        .filter( p -> p.endsWith( ".toml" ) )
        .map( p -> Try.of(() -> Toml.parse( p )))
        .map( Try::getOrNull )
        .filter( Objects::nonNull );
```

which is way nicer than you'd write otherwise, this might be better? I guess it's arguably actually longer,  easier to read, imho.

```java
      Files.list(configDir)
        .filter( Files::isRegularFile )
        .filter( Files::isReadable )
        .filter( p -> p.endsWith( ".toml" ) )
        .map( TryClass.of(Toml::parse))
        .map( TryReturns::forMapOrNull )
        .filter( Objects::nonNull )
```

and could be implemented something like (obviously replace with `Try`, etc)

```java
 static class TryClass {
    static <T, R> Function<T, TryReturns<T, R>> of( CheckedFunction1<T,R> func ) {
      return t -> new TryReturns<>( func );
    }
  }

  static class TryReturns<T, R> {
    private final CheckedFunction1<T, R> val;

    TryReturns( CheckedFunction1<T,R> val ) {
      this.val = val;
    }

    Function<T,R> forMapOrNull() {
        return t -> {
          try {
            return val.apply( t );
          }
          catch ( Throwable e ) {
            return null;
          }
        };
    }
  }
```

there may be another, even simpler, cleaner, solution, but this is what I came up with off the cuff. I mean, obviously even simpler would be to use more statics on `Try` but I'm kind of assuming that's not desirable.

**Comment by danieldietrich** [comment]
Hi and thank you for your suggestion!

I think we don't need this syntactic sugar. We would widen the API surface area without too much benefit.

Syntactically, it does not make a difference if we call `Try::getOrNull` vs `TryReturns::forMapOrNull`. The only difference that remains is `p -> Try.of(() -> Toml.parse( p ))` vs `TryClass.of(Toml::parse)`.

It would be sufficient to introduce something on the lines like:

```java
static <T, R> Function<T, Try<R>> mapToTry(CheckedFunction1<T, R> f) {
    return t -> Try.of(() -> f(t));
}
```

Then we would have:

```diff
Files.list(configDir)
        .filter( Files::isRegularFile )
        .filter( Files::isReadable )
        .filter( p -> p.endsWith( ".toml" ) )
-        .map( p -> Try.of(() -> Toml.parse( p )) )
+        .map( mapToTry(Toml::parse) )
        .map( Try::getOrNull )
        .filter( Objects::nonNull );
```

But I don't see the benefit. It would be another layer of indirection at the cost of an increase in mental complexity. Sometimes it is better to be a few characters more explicit instead of hiding what happens behind the curtain.

I hope you understand it.
