### ISSUE TITLE
Try.withResources requires calling of, sillily

### ISSUE THREAD

**Issue by xenoterracide** [vavr-io/vavr#2620]
this seems silly

```java
     var config = Try.withResources( () -> Files.list(configDir) )
       .of( t -> t  )
       .getOrElse( Stream::empty )
```

not sure why I can't just call `getOrElse` directly, but of is the only thing exposed on the return.

**Comment by danieldietrich** [comment]
The reason is that Try.withResources is a **builder**, not a **factory**.

Don't bother too much, `Try.withResources` will disappear in 1.0. The idiomatic way is:

```java
var config = Try.of(() -> {
    try (var paths = Files.list(configDir)) {
        return paths;
    }
}).getOrElse( Stream::empty )
```

You can do that now with 0.10.3.

Background info: There are several reasons for removing the `withResources` API, most importantly

* runtime impact of builder pattern / additional instances
* blowing up the API in O(n), where n is the number of autocloseable resources.
* currently bound to 8 resources
* syntactic sugar, but weird when `of( t -> t )` is still needed

... compared to the idiomatic way:

* no runtime impact compared to the native solution
* no additional API required
* no bound of number of resources
* maybe some chars more to type (e.g. the explicit `return`) but familiar Java code

**Comment by xenoterracide** [comment]
should I be using 0.10.3 instead of 1.0.0-Alpha3?

**Comment by xenoterracide** [comment]
what you suggested didn't work. I had to put all through the collect into that try, otherwise the resource was closed before I could do it.

```
    var config = Try.of( () -> {
        try( var paths = Files.list( configDir.toAbsolutePath() ) ) {
          return paths.filter( Files::isRegularFile )
            .filter( Files::isReadable )
            .filter( p -> p.endsWith( ".toml" ) )
            .map( p -> Try.of(() -> Toml.parse( p )))
            .map( Try::getOrNull )
            .filter( Objects::nonNull )
            .map( TomlParseResult::toMap )
            .reduce( Map.of(), (acc, a) -> {
              acc.putAll( a );
              return Map.copyOf( acc );
            } );
        }
      }).getOrElseThrow( t -> new RuntimeException(t));```

**Comment by danieldietrich** [comment]
> should I be using 0.10.3 instead of 1.0.0-Alpha3?

yes, definitely. Alpha is always subject to change. It will break your code.

> what you suggested didn't work

I did it from the top of my head without compiler support. I wanted to showcase the idea to use a native try-with-resources.
