### ISSUE TITLE
Rethrow exceptions from Futures

### ISSUE THREAD

**Issue by galegofer** [vavr-io/vavr#2637]
Having the next code using a Future in Vavr 0.10.3:

```
return Future.fromCompletableFuture(javaService.apply(request))
            .map(this::createResponse)
            .**onFailure(throwable -> {
                throw new RuntimeException(throwable);
            })**             
            .toCompletableFuture();
```

I would like to have a method on Future to be able to handle exceptions, and then being able to re-throw them, without the need to add a block method throwing the exception as displayed above.

 **.onFailure()** is not useful because it needs a Consumer and adding a block is basically a kind of hack.
**.getOrElseThrow()** neither because you don't have the initial exception.      

I think a solution may look like that:

```
return Future.fromCompletableFuture(javaService.apply(request))
            .map(this::createResponse)
            // onFailureReThrow will rethrow the exception not just created it.
            **.onFailureReThrow(RuntimeException::new)**             
            .toCompletableFuture();
```

or a more logical, and similar to Try.

```
return Future.fromCompletableFuture(javaService.apply(request))
            .map(this::createResponse)
            .onFailure(throwable -> log.error(throwable))
            **.getOrElseThrow(RuntimeException::new)**             
            .toCompletableFuture();
```

Makes sense, or there is another simpler way to accomplish what I want?

Thanks!

**Comment by qux42** [comment]
maybe something like this:
```
failed.recoverWith(t -> Future.failed(new RuntimeException(t)))
      .toCompletableFuture();

```

**Comment by danieldietrich** [comment]
Vavr intends to make your programs more safe by capturing state, including exceptional state. The `getOrElseThrow` method you mentioned is a terminal operation that converts the captured state back by getting the value or throwing.

What you suggest is more like breaking the fluent API by throwing in the middle of something. That isn't how our APIs are intended to be used.

You call `.toCompletableFuture()`, which calls `completableFuture.completeExceptionally(exception)` in the erroneous case. The `completableFuture` will throw an `ExecutionException` that wraps the original exception on a `.get()` call. I suggest to change the control flow of your program accordingly.

I also don't see the reason for using Vavr's `Future`. You could use `CompletableFuture.thenApply()` instead of `Future.map()`.
