### ISSUE TITLE
@Deprecate things scheduled to be removed in 1.0

### ISSUE THREAD

**Issue by xenoterracide** [vavr-io/vavr#2646]
As I've been told in issues earlier some things are not going to be in 1.0, it would be nice if these things were `@Deprecated` so people would know not to use them.

**Comment by danieldietrich** [comment]
It is still in the flow a bit. Probably you would not recognize most of the changes. Some APIs will be renamed, see below.

* Instead of removing the match API, it will move to its own module and won't be part of the Vavr core jar anymore. You might still use it but I suggest to move to Java's native pattern matching when it is available.
* The conversion methods `Value.toXxx` will be moved to the controls and to the collections, depending of their purpose. Collections can still be created from iterables. It makes not much sense to convert a collection to an Option or a Try.
* Semantically duplicate API within Option, Try and Either will be fused. But the functionality will still remain, so there will exist a migration path.

There will probably no additional release before 1.0, so there is no chance to deprecate the API.

**Comment by pivovarit** [comment]
I consider this done - all the deprecated APIs will be properly marked
