### ISSUE TITLE
Perf of Vector.of(T element)

### ISSUE THREAD

**Issue by tvelka** [vavr-io/vavr#2656]
What is the rationale behind `Vector.of(T element)` method? It performs terribly compared to its varargs cousin `Vector.of(T ... element)`, which builds a trie directly from the elements array.

**Comment by danieldietrich** [comment]
I see. Currently we have:

```java
public static <T> Vector<T> of(T element) {
    return ofAll(Iterator.of(element));
}
```

The following solution might perform better (needs to be verified):

```java
public static <T> Vector<T> of(T element) {
    return ofAll(BitMappedTrie.ofAll(new Object[] { element }));
}
```

Any volunteers for creating a PR?

**Comment by sleepytomcat** [comment]
Pull request here https://github.com/vavr-io/vavr/pull/2659

**Comment by danieldietrich** [comment]
Another word about the rationale behind `Vector.of(T)`: you are right, `of(T)` exists on the API level, because it should prevent creating an array, like in the varargs factory method `of(T...)`. In our case `of(T)` is not really needed, because currently we internally wrap the element into an array. However, I would keep the API, the implementation might change/might be improved over time.
