### ISSUE TITLE
toOption() should be consistent with the result of Option.of()

### ISSUE THREAD

**Issue by szz0104** [vavr-io/vavr#2692]
https://github.com/vavr-io/vavr/blob/e43e44b683467d94df90b38b937db2eaaa6a2603/src/main/java/io/vavr/Value.java#L1187
Suggest to change to：
return (get() == null) ? Option.none() : Option.some(get());

**Comment by szz0104** [comment]
Although the state of Try only depends on a success or a failure of a computation, reflected by the types Success and Failure, null has nothing to do with that state , but should be consistent with the result of Option.of().

**Comment by danieldietrich** [comment]
We can't do that because Option wouldn't be monadic (read: composable) anymore. We align to the semantics of Scala's Option, not to that of Optional.

Please read also our [blog post](http://blog.vavr.io/the-agonizing-death-of-an-astronaut/) on that topic.

Further reading:

* [Why java.util.Optional is broken](https://blog.developer.atlassian.com/optional-broken/) by Atlassian (2015)
* [How Optional Breaks the Monad Laws and Why It Matters](https://www.sitepoint.com/how-optional-breaks-the-monad-laws-and-why-it-matters/) by Marcello La Rocca (2016)

Vavr is here to make a difference in the space of functional programming with Java. Sometimes this means to fix the broken Java standard library.

Thank you for your question, this is important! However, I will close this issue because we can't change the behavior without braking core functionality (like the For-comprehension).
