### ISSUE TITLE
Default ExecutorService for Futures

### ISSUE THREAD

**Issue by ChristerF** [vavr-io/vavr#821]
Firstly - great job with Javaslang! I had one question on the choice of default executor service. I noticed that you picked the ForkJoinPool.commonPool as your default ExecutorService in Future.java. I was just wondering if you ever considered making a direct (same thread) ExecutorService the default executorService? There is nothing wrong with the common pool, but in a fully async solution it forces an unnecessary context switch for each callback. I know it is all pluggable, but wondering if this was a conscious decision. 

Also, if you could get away with an Executor instead of an ExecutorService it would mean less overhead in general.

Maybe it is possible to abstract the ExecutorService away somehow - as an interface it is fairly heavyweight for what it does.

Just $0.02 cents on the concurrent part. Looking forward to your thoughts.

Thanks,
Christer

**Comment by danieldietrich** [comment]
Hi Christer,

thank you! I considered the `ForkJoinPool.commonPool` as default because Scala's default `ExecutorContext.global` is also backed by a ForkJoinPool. My goal is to that Java and Scala developers can switch languages forth/back without much effort. The naming scheme (packages collection and control) is also aligned to Scala in Javaslang.

Yes, having an Executor instead of an ExecutorService would be much nicer. Currently we need the ExecutorService for our cancel-feature. The ExecutorService returns a Java Future which is cancelable. But You're right, it would be much nicer to implement the cancel-feature ourselves.

Because of interoperability with Java in general it is nice to use Java's interfaces. We do this already for functions, e.g. Function, Supplier, Predicate et. al.

I will check it what we can do!

Many thanks,

Daniel

**Comment by danieldietrich** [comment]
You're also right about it that a single-thread ExecutorService would be the simplest solution we can imagine. But then it would not much sense to use Futures. The computations could be called directly because they are processed sequentially in a single-threaded context. We should use Java's default thread pool to obtain the simplest _concurrent_ context we can imagine.

**Comment by ChristerF** [comment]
Daniel - thanks for explaining the background on the design - I'm not a scala user myself. In Java 8's CompletableFuture, you specify sync/async for each type of Continuation where sync is "run in current or completion thread" and async is run by the common pool or a specified executor. 

To me, a Future in its pure form is primarily a synchronization primitive, not a means to run code asynchronously - but I realize the Scala futures and Java 8's CompletableFuture transforms it to a composer for asynchronous functions.

Regardless, it would be nice if there would be an easier way to specify "sync" than supplying a direct ExecutorService - something along the lines of CompletableFuture.

**Comment by danieldietrich** [comment]
I will move this issue to 2.0.1 to save some time for investigation and re-design of Future. Release 2.0.0 will have a Future that takes ExecutorService instead of Executor because of the cancel feature we use.

We still have the opportunity to change it API in the way that it uses Executor instead of ExecutorService without breaking it. It would just widen the domain of accepted values.

**Comment by asevans48** [comment]
Any idea on this? If we could replace Scala with JavaSlang that would be neat. Still, SBT with its continuous build is better.

**Comment by danieldietrich** [comment]
@asevans48 thank you for using Javaslang! Which change do you exactly need in order to replace Scala with Javaslang. Our current Future already has a default ExecutorService.

The one change that will differ from Scala is #1530. Currently Scala runs onComplete handlers on a new thread. We plan to reuse the existing thread, which completed and uses no more CPU.

I think you are already able to switch to Javaslang using our latest stable version 2.0.5.

**Comment by danieldietrich** [comment]
To recap:

> in a fully async solution it forces an unnecessary context switch for each callback

In #1530 we will change Future's behavior and execute callbacks on the same thread by default (this will be configurable). Using the the same thread for both, result computation and callbacks, will reduce the possibility of deadlocks (e.g. when no more threads are available on the pool etc.). Providing a special API for the sync/async case is an interesting idea. We will think about it in #1530 .

> if you could get away with an Executor instead of an ExecutorService it would mean less overhead 

We need the ExecutorService because we internally rely on java.util.concurrent.Future returned by submit().

---

I think we can close this ticket now because some ideas are covered by #1530.
